Họ và tên: **Nguyễn Ngọc Băng Tâm**

MSSV: **1712747**

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 1. Tập playlist

### a. Kiểm tra tổng quan 

In [18]:
raw_playlist = pd.read_csv("Crawl_data/playlists.csv", sep = '\t')

# Xóa cột index (chỉ đóng vai trò chỉ mục)
raw_playlist.drop(columns=['index'], inplace=True)

Tập playlist hiện tại có 2704 mẫu và 32 thuộc tính. Ta sẽ tiến hành tìm hiểu các thuộc tính và lựa chọn một số thuộc tính nhất định phục vụ cho câu hỏi mà ta quan tâm 

In [19]:
raw_playlist.shape

(2704, 32)

**Tóm tắt:**

|Thuộc tính|Kiểu dữ liệu|     Ý nghĩa   |Miền giá trị |
|:--------:|:-------------:|:-----:|:-----:|
|**artwork_url**|Chuỗi |Đường dẫn đến ản đại diện của playlist||
|**created_at**|Thời gian|Thời gian khởi tạo playlist|   |
|**description**|Chuỗi|Mô tả playlist của người đăng tải| |
|**duration**|Số nguyên|Tổng thời gian các track nhạc trong playlist|Liên tục (đơn vị: mili giây)|
|**embeddable_by**|Chuỗi|Đối tượng có quyền nhúng track hoặc playlist này|"all" (tất cả mọi người), "me" (chỉ mình tôi) hoặc None (không ai)|
|**genre**|Chuỗi|Thể loại nhạc của playlist|   |
|**id**|Kiểu phân loại|Định danh của playlist||
|**kind**|Chuỗi|Loại đối tượng|playlist|
|**label_name**|Chuỗi|Hãng thu âm|   |
|**last_modified**|Thời gian|Lần chỉnh sửa cuối cùng|   |
|**license**|Chuỗi|Giấy phép Creative Commons|“no-rights-reserved”, “all-rights-reserved”, “cc-by”, “cc-by-nc”, “cc-by-nd”, “cc-by-sa”, “cc-by-nc-nd”, “cc-by-nc-sa”|
|**likes_count**|Số nguyên|Số lượt yêu thích của playlist|Liên tục|
|**managed_by_feeds**|Luận lý|Playlist có được quản lý bởi RSS feed|True hoặc False|
|**permalink**|Chuỗi|Đường dẫn cố định của tài nguyên|   |
|**permalink_url**|Chuỗi|Đường dẫn đến trang Soundcloud    |   |
|**public**|Luận lý|Playlist có công khai hay không|True hoặc False. Trong dataset chỉ chứa playlist có giá trị True do chỉ rút trích được các playlist chia sẻ công khai|
|**purchase_title**|Chuỗi|     |
|**purchase_url**|Chuỗi|       |
|**release_date**|Thời gian|Thời gian xuất bản playlist|   |
|**reposts_count**|Số nguyên|Số lượt đăng lại playlist| Liên tục  |
|**secret_token**|Chuỗi|   |
|**sharing**|Chuỗi|Chế độ chia sẻ công khai hoặc riêng tư|public, private|
|**tag_list**|Chuỗi|Danh sách các tag của playlist|   |
|**title**|Chuỗi|Tiêu đề playlist|    |
|**uri**|Chuỗi|Đường dẫn API của playlist|    |
|**user_id**|Kiểu phân loại|Định danh của người sở hữu playlist|   |
|**set_type**|Chuỗi|Định dạng đĩa|"album", "compilation", "ep", "single"|
|**is_album**|Luận lý|Playlist có phải album hay không|True hoặc False|
|**published_at**|Thời gian|Thời điểm đăng tải playlist|   |
|**display_date**|Thời gian|Thời điểm playlist hiển thị|   |
|**track_counts**|Số nguyên|Số lượng track trong playlist|Liên tục |
|**tracks**|Chuỗi|Danh sách id của các track trong playlist|   |

#### a.1. Kiểm tra các thuộc tính định danh

In [24]:
print(f"Số lượng id: {raw_playlist['id'].nunique()}")
print(f"Số lượng permalink_url: {raw_playlist['permalink_url'].nunique()}")
print(f"Số lượng uri: {raw_playlist['uri'].nunique()}")      

Số lượng id: 2704
Số lượng permalink_url: 2704
Số lượng uri: 2704


#### a.2. Kiểm tra các thuộc tính không đóng góp đáng kể vào EDA

In [44]:
print(f"Số lượng artwork_url: {raw_playlist['artwork_url'].nunique()}\n") 

# kind
print(f"Số lượng kind: {raw_playlist['kind'].nunique()}")
print(f"Giá trị của thuộc tính kind: {raw_playlist['kind'].unique()}\n")
      
# secret_token
print(f"Số lượng secret_token: {raw_playlist['secret_token'].nunique()}")   
print(f"Giá trị của secret_token: {raw_playlist['secret_token'].unique()}\n")  
      
# public
print(f"Số lượng public: {raw_playlist['public'].nunique()}")   
print(f"Giá trị của public: {raw_playlist['public'].unique()}\n")         
      
# sharing
print(f"Số lượng sharing: {raw_playlist['sharing'].nunique()}")   
print(f"Giá trị của sharing: {raw_playlist['sharing'].unique()}\n")  

# tag_list
print(f"Số lượng tag_list: {raw_playlist['tag_list'].nunique()}\n")   
# print(f"Giá trị của tag_list: {raw_playlist['tag_list'].unique()}")  

# description
print(f"Số lượng description: {raw_playlist['description'].nunique()}")   
# print(f"Giá trị của tag_list: {raw_playlist['description'].unique()}")  

Số lượng artwork_url: 467

Số lượng kind: 1
Giá trị của thuộc tính kind: ['playlist']

Số lượng secret_token: 0
Giá trị của secret_token: [nan]

Số lượng public: 1
Giá trị của public: [ True]

Số lượng sharing: 1
Giá trị của sharing: ['public']

Số lượng tag_list: 442

Số lượng description: 453


#### a.3. Kiểm tra các thuộc tính tương đồng

In [45]:
print(f"Số lượng created_at: {raw_playlist['created_at'].nunique()}")
print(f"Số lượng release_date: {raw_playlist['release_date'].nunique()}")
print(f"Số lượng published_at: {raw_playlist['published_at'].nunique()}")    
print(f"Số lượng display_date: {raw_playlist['display_date'].nunique()}")      

Số lượng created_at: 2703
Số lượng release_date: 318
Số lượng published_at: 2347
Số lượng display_date: 2690


Khi xem xét 4 thuộc tính `created_at`, `release_date`, `published_at`, `display_date`, có thể thấy chúng khá liên quan nhau. 
- `created_at` là thời điểm người đăng tải **bắt đầu khởi tạo** playlist
- `published_at` là thời điểm người đăng tải nhấn **phát hành** playlist
- `displate_date` là thời điểm playlist thực sự hiển thị sau khi được người đăng tải phát hành
- `release_date` là thời điểm người đăng tải **dự kiến phát hành** playlist (set trước 1 thời điểm nhất định)

Đồ án chỉ xét thời điểm playlist thực sự hiển thị công khai trên Soundcloud, tức chỉ chọn thuộc tính `display_date`

In [50]:
raw_playlist[['created_at', 'release_date', 'published_at', 'display_date']].tail()

created_at          release_date          published_at  \
2699  2020-10-04T05:03:56Z                   NaN  2020-10-04T05:03:56Z   
2700  2018-11-02T22:11:44Z  2018-11-08T00:00:00Z  2018-11-09T05:00:32Z   
2701  2019-01-25T00:26:59Z  2019-01-25T00:00:00Z  2019-01-25T00:00:00Z   
2702  2020-05-09T03:06:04Z                   NaN  2020-05-09T05:05:50Z   
2703  2018-10-22T09:08:13Z  2018-10-23T00:00:00Z  2018-10-22T15:00:04Z   

              display_date  
2699  2020-10-04T05:03:56Z  
2700  2018-11-09T05:00:32Z  
2701  2019-01-25T00:00:00Z  
2702  2020-05-09T05:05:50Z  
2703  2018-10-22T15:00:04Z

#### a.4 Kiểm tra các thuộc tính còn lại

In [66]:
# duration
print(f"Số lượng duration: {raw_playlist['duration'].nunique()}\n")

# embeddable_by
print(f"Số lượng embeddable_by: {raw_playlist['embeddable_by'].nunique()}")
print(f"Giá trị của embeddable_by: {raw_playlist['embeddable_by'].unique()}\n")  

      
# genre
print(f"Số lượng genre: {raw_playlist['genre'].nunique()}\n")
      
# label_name
print(f"Số lượng label_name: {raw_playlist['label_name'].nunique()}\n")

# last_modified
print(f"Số lượng last_modified: {raw_playlist['last_modified'].nunique()}\n")
      
# license
print(f"Số lượng license: {raw_playlist['license'].nunique()}")
print(f"Giá trị của license: {raw_playlist['license'].unique()}\n")  
      
      
# likes_count
print(f"Số lượng likes_count: {raw_playlist['likes_count'].nunique()}\n")
      
# managed_by_feeds
print(f"Số lượng managed_by_feeds: {raw_playlist['managed_by_feeds'].nunique()}")
print(f"Giá trị của managed_by_feeds: {raw_playlist['managed_by_feeds'].unique()}\n")  
     
# permalink
print(f"Số lượng permalink: {raw_playlist['permalink'].nunique()}\n")      
      
# purchase_title
print(f"Số lượng purchase_title: {raw_playlist['purchase_title'].nunique()}\n")   

# purchase_url
print(f"Số lượng purchase_url: {raw_playlist['purchase_url'].nunique()}\n") 
      
# reposts_count
print(f"Số lượng reposts_count: {raw_playlist['reposts_count'].nunique()}\n") 

# title
print(f"Số lượng title: {raw_playlist['title'].nunique()}\n") 

# user_id
print(f"Số lượng user_id: {raw_playlist['user_id'].nunique()}\n") 

# set_type
print(f"Số lượng set_type: {raw_playlist['set_type'].nunique()}") 
print(f"Giá trị của set_type: {raw_playlist['set_type'].unique()}\n")  

# is_album
print(f"Số lượng is_album: {raw_playlist['is_album'].nunique()}") 
print(f"Giá trị của is_album: {raw_playlist['is_album'].unique()}\n")  

# display_date
print(f"Số lượng display_date: {raw_playlist['display_date'].nunique()}\n") 

# track_counts
print(f"Số lượng track_counts: {raw_playlist['track_counts'].nunique()}\n") 

# track
print(f"Số lượng track: {raw_playlist['tracks'].nunique()}\n") 

Số lượng duration: 2119

Số lượng embeddable_by: 3
Giá trị của embeddable_by: ['all' 'none' 'me']

Số lượng genre: 157

Số lượng label_name: 38

Số lượng last_modified: 2694

Số lượng license: 5
Giá trị của license: ['all-rights-reserved' 'cc-by-nc-sa' 'cc-by' 'cc-by-nc-nd' 'cc-']

Số lượng likes_count: 910

Số lượng managed_by_feeds: 2
Giá trị của managed_by_feeds: [False  True]

Số lượng permalink: 927

Số lượng purchase_title: 24

Số lượng purchase_url: 55

Số lượng reposts_count: 560

Số lượng title: 1287

Số lượng user_id: 1754

Số lượng set_type: 4
Giá trị của set_type: [nan 'album' 'compilation' 'ep' 'single']

Số lượng is_album: 2
Giá trị của is_album: [False  True]

Số lượng display_date: 2690

Số lượng track_counts: 455

Số lượng track: 2122



Xem thử số lượng của từng giá trị

In [88]:
raw_playlist['label_name'].value_counts()

TenThousand Projects, LLC                             4
Cinematic Music Group                                 2
6ix9ine, distributed by Create Music Group            2
DiviSoul                                              2
Tik Tok Songs                                         2
Generation Now 2016                                   1
Shop FMM LLC                                          1
Winners Circle Entertainment Inc /EMPIRE              1
Internet Money Records / TenThousand Projects, LLC    1
One Umbrella Records                                  1
KSR Group                                             1
300 Entertainment                                     1
Winners Cirlce Entertainment / EMPIRE                 1
MAU Records                                           1
AUTNMY under license to Columbia Records              1
Mugatunes                                             1
Columbia Records                                      1
300 Entertainment / Quality Control Music       

In [86]:
raw_playlist['permalink'].value_counts()

russ                             10
said-sum-moneybagg               10
sex-sounds-lil-tjay              10
sofia-clairo-slowed              10
sweater-weather                  10
                                 ..
xxxtentacion-presents-members     1
14-with-a-dream                   1
bring-em-out-calboy               1
yeahh                             1
life-of-betrayal                  1
Name: permalink, Length: 927, dtype: int64

In [87]:
raw_playlist['title'].value_counts()

ppcocaine                   10
capitalize off pain         10
sofia clairo slowed         10
bookbag 2 0                 10
train wreck james arthur    10
                            ..
✨Mulatto✨                    1
Nectar                       1
Certified Hitmaker           1
DOJA                         1
F*CK LOVE (SAVAGE)           1
Name: title, Length: 1287, dtype: int64

In [89]:
raw_playlist['purchase_title'].value_counts()

Stream/Download           8
Download                  6
Stream                    6
DOWNLOAD                  3
// D O W N L O A D        3
Buy                       2
❤️mell-ø Mix Youtube❤️    2
Stream/download           1
SPOTIFY  🚫💩🎧              1
BUY NOW, Do it ;)         1
Rake // Hexada Video      1
itunes                    1
D O W N L O A D           1
iTunes                    1
Dowload the mixtape       1
stream / download         1
BUY ON ITUNES             1
Purchase                  1
BUY NOW ON ITUNES         1
Buy on iTunes             1
DOWNLOAD NOW              1
stream/download NOVA      1
Download Mixtape Now      1
❤️mell-ø mix❤️            1
Name: purchase_title, dtype: int64

In [90]:
raw_playlist['purchase_url'].value_counts()

http://www.davidsanyabeats.com                                                                  3
https://www.youtube.com/c/LofiHipHopBeats?sub_confirmation=1                                    2
http://youngboynba.lnk.to/AIYOUNGBOY2So                                                         1
https://ABoogie.lnk.to/hoodieszn                                                                1
https://yungeenace.ffm.to/chloe.pbt                                                             1
https://music.apple.com/us/album/dont-sleep/1484726272                                          1
http://fanlink.to/NudyLand                                                                      1
https://criminalbassline.com/goodie-daniel-jaeger-the-job-without-me-eminem-tribute             1
https://fanlink.to/mugatunes-spotify                                                            1
https://itunes.apple.com/us/album/tell-me-single/id887871018                                    1
https://itunes.apple

In [91]:
raw_playlist['embeddable_by'].value_counts()

all     2420
none     282
me         2
Name: embeddable_by, dtype: int64

In [93]:
raw_playlist['license'].value_counts()

all-rights-reserved    2693
cc-by                     6
cc-by-nc-sa               3
cc-                       1
cc-by-nc-nd               1
Name: license, dtype: int64

In [94]:
raw_playlist['managed_by_feeds'].value_counts()

False    2630
True       74
Name: managed_by_feeds, dtype: int64

**Nhận xét:**
- `set_type` và `is_album` tương đồng nên chỉ cần chọn trường `set_type`
- `purchase_url` sẽ được dùng để tạo trường mới là `is_purchasable` (playlist có mục đích thương mại hay không, nếu giá trị `purchase_url` khác null tức playlist đó nhằm mục đích thương mại)
- `embeddable_by` chủ yếu chứa giá trị `all`, `license` chủ yếu chứa giá trị `all-rights-reserved` nên độ mất cân bằng các phân lớp lớn => không chọn cho quá trình EDA

- Các thuộc tính `managed_by_feeds`, `last_modified`, `permalink`, `purchase_title` và `title`, `label_name` cũng không chọn cho bước EDA


#### a.5 Tổng kết

- Thuộc tính `index` là cột chỉ mục. 
- Đối tượng playlist có 31 thuộc tính, trong đó bao gồm 4 loại thuộc tính chính:
    - Các thuộc tính định danh => Chỉ chọn `id`
        - `id`    
        - `permalink_url`
        - `uri`
       
    - Các thuộc tính không đóng góp đáng kể vào quá trình EDA => Không chọn
        - `artwork_url`
        - `kind`
        - `secret_token`
        - `public`
        - `sharing`
        - `tag_list`
        - `description`
      
    - Các thuộc tính khá liên quan nên chỉ cần giữ lại 1 trong số chúng
        - `created_at`, `release_date`, `published_at` và `display_date` => Tạm chọn giữ lại `display_date`
        
    - Các thuộc tính còn lại:
        - `duration`
        - `embeddable_by`
        - `genre`
        - `label_name`
        - `last_modified`
        - `license`
        - `likes_count`
        - `managed_by_feeds`
        - `permalink`
        - `purchase_title`
        - `purchase_url`
        - `reposts_count`
        - `title`
        - `user_id`
        - `set_type`
        - `is_album`
        - `display_date`
        - `track_counts`
        - `tracks`
        
- Cuối cùng, đồ án chọn 11 thuộc tính của tập playlist để EDA:
    - `id`
    - `duration`
    - `genre`
    - `likes_count`
    - `is_purchasable` (feature engineer từ `purchase_url`)
    - `reposts_count`
    - `user_id`
    - `set_type` 
    - `display_time` (feature engineer từ `display_date`, mang ý nghĩa là thời gian playlist đã hiển thị tính tới thời điểm ngày 05/11/2020)
    - `track_counts`
    - `tracks`



In [1037]:
selected_columns = ['id', 'duration', 'genre', 'likes_count', 'purchase_url', 'reposts_count', 
                   'user_id', 'set_type', 'display_date', 'track_counts', 'tracks']
selected_playlist = raw_playlist[selected_columns]

### b. Tiền xử lý và feature engineer

In [1038]:
selected_playlist.head()

id  duration genre  likes_count purchase_url  reposts_count  \
0   310741832  40935252   NaN         2035          NaN            103   
1  1143112054  37740984   NaN            0          NaN              0   
2   971808526  15552646   NaN           12          NaN              0   
3   149404857  66544676   NaN          234          NaN             28   
4   361670771   9427177   NaN         5548          NaN            278   

     user_id set_type          display_date  track_counts  \
0  273587555      NaN  2017-03-27T09:59:33Z           189   
1  667588841      NaN  2020-10-10T04:28:26Z           181   
2  769710073      NaN  2020-01-22T16:32:34Z            76   
3  177229326      NaN  2015-09-28T08:34:17Z           203   
4  339239709      NaN  2017-10-21T14:37:16Z            50   

                                              tracks  
0  111350611,127711350,89291705,221922037,2557906...  
1  877524697,877524238,877523905,877523803,877523...  
2  547941324,5284026,579807702,685678354,33010377...  
3  19320434,215361560,216352962,43248780,21468388...  
4  332962988,333923891,329430750,335860168,308016...

#### b.1. Kiểm tra giá trị không hợp lệ

Ta thực hiện kiểm tra sự không hợp lệ và không đồng nhất (cùng một từ nhưng từ viết hoa, từ viết thường,...) với các trường dữ liệu kiểu `categorical` là `genre`.

Soundcloud chỉ chứa 41 thể loại nhạc chính thức [(Tham khảo)](https://gist.github.com/Thinkscape/8b98b82a74c102b31f5d) nhưng các giá trị unique của genre lại đạt đến 157    

In [1039]:
selected_playlist['genre'].nunique()

157

In [1040]:
genre_lst = ['Alternative Rock',
            'Ambient',
            'Audiobooks',
             'Business',
             'Classical',
             'Comedy',
             'Country',
             'Dance & EDM',
             'Dancehall'
             'Deep House'
             'Disco',
             'Drum & Bass',
             'Dubstep',
             'Electronic',
             'Entertainment',
             'Folk & Singer-Songwriter',
             'Hip Hop & Rap',
             'House',
             'Indie',
             'Jazz & Blues',
             'Latin',
             'Learning',
             'Metal',
             'News & Politics',
             'Piano',
             'Pop',
             'R&B & Soul', 
             'Reggae', 
             'Reggaeton',
             'Religion & Spirituality',
             'Rock',
             'Science',
             'Soundtrack',
             'Sports',
             'Storytelling',
             'Techno',
             'Technology',
             'Trance',
             'Trap', 
             'Trending Audio',
             'Trending Music',
             'Trip Hop',
             'World']
print(f"Số lượng genre của Soundcloud: {len(genre_lst)}")

Số lượng genre của Soundcloud: 41


In [1041]:
selected_playlist['genre'].sort_values().unique()

array(['1017 ', '14WITHADREAM', '2014 Festival Anthem ;)', '21 Savage',
       '21-savage', 'A BOOGIE WIT DA HOODIE', 'Alternative',
       'Alternative Rock', 'BYLU.THOAT', 'Billie Eilish', 'Brent Faiyaz',
       'Calboy', 'Chill', 'Chillout', 'Country', 'DA BABY', 'DaBaby',
       'Dance', 'Dance & EDM', 'Delusional Thomas', 'Doja Cat',
       'Drake Laugh Now Cry Later', 'Dubstep', 'Electronic',
       'Entertainment', 'Excitement Trippie redd',
       'For The Night Pop Smoke', 'Frank Ocean', 'French Hip Hop',
       'Hip Hop', 'Hip Hop/Rap', 'Hip hop', 'Hip hop y Rap', 'Hip-Hop',
       'Hip-hop & Rap', 'Hip-hop/rap', 'Hiphop', 'House', 'Iann Dior',
       'Indie', 'JACK HARLOW', 'JESUSISKING', 'Juice WRLD', 'Kpop',
       'LAFLAME', 'LIL DARKIE', 'LIL PEEP', 'LIL TECCA', 'LILMOSEY',
       'LUV', 'Latin', 'Latin Music', 'Lets Link', 'Lifestyle R&B',
       'Lil Baby', 'Lil Tecca', 'Lil Tjay', 'Lil Wayne', 'Lo-fi', 'Lofi',
       'Lofi Chill Relax', 'MONEYBAGG YO', 'MoneyBagg Yo',

In [1042]:
invalid_genres = {'1017 ', '14WITHADREAM', '2014 Festival Anthem ;)', '21 Savage', '21-savage', 'A BOOGIE WIT DA HOODIE',
                 'BYLU.THOAT', 'Billie Eilish', 'Brent Faiyaz', 'Calboy', 'Chill', 'Chillout', 'DA BABY', 'DaBaby',
                 'Delusional Thomas', 'Doja Cat', 'Drake Laugh Now Cry Later', 'Excitement Trippie redd', 
                  'For The Night Pop Smoke', 'Frank Ocean', 'Iann Dior', 'LAFLAME', 'LIL DARKIE', 'LIL PEEP', 'LIL TECCA', 
                  'LILMOSEY','LUV', 'Lets Link', 'Lil Baby', 'Lil Tecca', 'Lil Tjay', 'Lil Wayne', 'MONEYBAGG YO', 'MoneyBagg Yo',
                   'Mood Swings Pop Smoke', 'Mulatto', 'NBA YoungBoy', 'NLE Choppa', 'POLO G', 'Playboi Carti Leaks',
                  'Post Malone', 'RM,', 'ROD WAVE', 'Real Street Shit', 'Rod Wave', 'Roddy Ricch', 'SHORELINE MAFIA',
                 'Swavey','TGOD', 'Tacquitos', 'The Kid Laroi', 'Travis Scott', 'Travis Scott Unreleased', 'Trippie Redd',
                   'Unreleased Don Toliver', 'Unreleased Drake', 'Unreleased Juice Wrld', 'Unreleased Lil Uzi Vert',
                   'Unreleased Trippie Redd', 'Unreleased Xxxtentacion', 'VOID','What You Know About Love Pop Smoke',
                 'YNW Melly', 'Ynw Melly', 'Young Thug', 'YoungBoy Never Broke Again','Yung Bleu','astroworld travis scott', 
                  'cigarettes juice wrld', 'clairo', 'coffin lil yachty','country,rap,metal', 'dirty', 'doja cat unreleased', 
                  'g herbo', 'iann dior', 'lil mosey', 'lil skies', 'lilpeep', 'mac miller', 'memes', 'mood', 'nocopyrightsounds', 'offonoff',
               'playboi carti', 'playboicarti', 'pop smoke','pop smoke unreleased','scfirst', 'tory lanez', 'wap cardi b', 'whoopty cj',
               'wishing well juice wrld', 'woah lil baby', 'youngthug', '☿', 'JACK HARLOW', 'JESUSISKING', 'Juice WRLD'}


In [1043]:
selected_playlist['genre'].isnull().sum()

2157

In [1044]:
for index, row in selected_playlist.iterrows():
    # chỉ xét các dòng có genre <> NaN
    if not pd.isna(row['genre']):
        if row['genre'] in invalid_genres:
            selected_playlist.loc[index, 'genre'] = np.NaN

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


In [1045]:
# Số lượng giá trị NaN tăng lên do ta đã loại bỏ các giá trị không phải genre
selected_playlist['genre'].isnull().sum()

2266

In [1046]:
# Xử lý các trường hợp không đồng nhất viết hoa-thường
selected_playlist['genre'] = selected_playlist['genre'].str.lower();
selected_playlist['genre'].sort_values().unique()

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array(['alternative', 'alternative folk', 'alternative rock', 'country',
       'dance', 'dance & edm', 'dubstep', 'electronic', 'entertainment',
       'french hip hop', 'hip hop', 'hip hop y rap', 'hip hop/rap',
       'hip-hop', 'hip-hop & rap', 'hip-hop/rap', 'hiphop', 'house',
       'indie', 'kpop', 'latin', 'latin music', 'lifestyle r&b', 'lo-fi',
       'lofi', 'lofi chill relax', 'lofi hip hop', 'nightcore', 'party',
       'pbr&b', 'pop', 'punk christmas', 'r & b', 'r&b', 'r&b & soul',
       'rap', 'rap hiphop', 'rap ♥', 'rap/hip hop', 'reggae',
       'regional mexicano', 'remixes', 'rock', 'sad', 'sad songs',
       'shadow rap', 'slowed and reverb', 'tik tok songs', 'trap',
       'world', nan], dtype=object)

In [1047]:
# Xử lý không đồng nhất về chính tả
spelling = {'french hip hop':'hip hop/rap',
            'hip hop':'hip hop/rap',
            'hip hop y rap':'hip hop/rap',
            'hip-hop':'hip hop/rap',
            'hip-hop & rap':'hip hop/rap',
            'hip-hop/rap':'hip hop/rap', 
            'hiphop':'hip hop/rap',
            'rap':'hip hop/rap',
            'rap hiphop':'hip hop/rap', 
            'rap ♥':'hip hop/rap', 
            'rap/hip hop':'hip hop/rap',
            'latin music': 'latin', 
            'lifestyle r&b':'r&b & soul',
            'pbr&b':'r&b & soul', 
            'r & b':'r&b & soul', 
            'r&b':'r&b & soul', 
           'lofi':'lo-fi',
            'lofi chill relax':'lo-fi',
            'lofi hip hop':'lo-fi', 
            'slowed and reverb':'remixes',
           'sad songs':'sad'}

selected_playlist['genre'] = selected_playlist['genre'].replace(spelling)
selected_playlist['genre'].sort_values().unique()

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


array(['alternative', 'alternative folk', 'alternative rock', 'country',
       'dance', 'dance & edm', 'dubstep', 'electronic', 'entertainment',
       'hip hop/rap', 'house', 'indie', 'kpop', 'latin', 'lo-fi',
       'nightcore', 'party', 'pop', 'punk christmas', 'r&b & soul',
       'reggae', 'regional mexicano', 'remixes', 'rock', 'sad',
       'shadow rap', 'tik tok songs', 'trap', 'world', nan], dtype=object)

In [1048]:
selected_playlist['genre'] = selected_playlist['genre'].str.capitalize();

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [1049]:
# Kiểm tra sau khi xử lý các genre nhạc không hợp lệ
selected_playlist['genre'].sort_values().unique()

array(['Alternative', 'Alternative folk', 'Alternative rock', 'Country',
       'Dance', 'Dance & edm', 'Dubstep', 'Electronic', 'Entertainment',
       'Hip hop/rap', 'House', 'Indie', 'Kpop', 'Latin', 'Lo-fi',
       'Nightcore', 'Party', 'Pop', 'Punk christmas', 'R&b & soul',
       'Reggae', 'Regional mexicano', 'Remixes', 'Rock', 'Sad',
       'Shadow rap', 'Tik tok songs', 'Trap', 'World', nan], dtype=object)

#### b.2. Kiểm tra giá trị null (missing value)

In [1050]:
selected_playlist.isnull().sum()

id                  0
duration            0
genre            2266
likes_count         0
purchase_url     2646
reposts_count       0
user_id             0
set_type         2325
display_date        0
track_counts        0
tracks             19
dtype: int64

Ta tiến hành xử lý giá trị null của 4 thuộc tính: `genre`, `purchase_url`, `set_type` và `tracks`

##### b1.1. purchase_url

- Với trường `purchase_url`, nếu playlist có `purchase_url` khác null thì trường `is_purchasable = True`, ngược lại `is_purchasable = False`
- Sau khi tạo trường `is_purchasable` ta xóa cột `purchase_url`

In [1051]:
selected_playlist.loc[~selected_playlist['purchase_url'].isnull(), 'is_purchasable'] = True

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)


In [1052]:
selected_playlist.loc[selected_playlist['purchase_url'].isnull(), 'is_purchasable'] = False

In [1053]:
selected_playlist = selected_playlist.drop(columns=['purchase_url'])

In [1054]:
print(f"Số giá trị null trường is_purchasable: {selected_playlist['is_purchasable'].isnull().sum()}")

Số giá trị null trường is_purchasable: 0


##### b1.2. set_type

- Với trường `set_type`, các playlist không phải album, compilation hay episode thì ta sẽ fill bằng giá trị `normal_playlist`

In [1055]:
set_type_na = {'set_type':'normal_playlist'}
selected_playlist = selected_playlist.fillna(value=set_type_na)

In [1056]:
# Test sau khi fillna
print(f"Số giá trị null trường set_type: {selected_playlist['set_type'].isnull().sum()}")
print(f"Các giá trị trường set_type: {selected_playlist['set_type'].unique()}")      

Số giá trị null trường set_type: 0
Các giá trị trường set_type: ['normal_playlist' 'album' 'compilation' 'ep' 'single']


##### b1.3. tracks

- Với trường `tracks`, có thể các playlist có trường này bằng null là những playlist không chứa track nào, nên ta sẽ thay trường `tracks = " "` (tức chuỗi rỗng).
- Sau khi thực hiện kiểm tra, quả thật các playlist có `tracks = NaN` không chứa track nào, do đó đáng lẽ ra trường `duration` của chúng phải bằng 0. 
- Ta sẽ kiểm tra `permalink_url` của các `id` này, nếu có trường hợp `tracks = NaN` và `duration <> 0` thì ta sẽ sửa lại trường `duration` của chúng cho thống nhất. 

**Lưu ý: Ta sử dụng api của Soundcloud để dò tìm permalink_url từ id chứ không sử dụng permalink_url trực tiếp từ dataframe gốc**

- Sau khi kiểm tra đường dẫn thực sự của các playlist này, rõ ràng chúng không chứa track nào nhưng trường `duration` lấy từ api vẫn khác 0. Ta sẽ điều chỉnh giá trị `duration = 0` và `tracks = " "` (chuỗi rỗng)

In [1057]:
# Lỗi không thống nhất: Các playlist không chứa tracks (track_counts = 0 và tracks = NaN) lại có duration <> 0
selected_playlist[(selected_playlist['tracks'].isnull())]

id  duration       genre  likes_count  reposts_count    user_id  \
146    369995528         0         NaN            7              0  204551380   
186      6668033    315849         NaN            0              0   24175139   
275     15500855    249309         NaN            1              0   61990827   
414     98000902    323242         NaN            0              0  143615197   
563     45791266   1102020  R&b & soul         7184           2251   21207090   
1171   224254822         0         NaN           59             11  225368471   
1197   111914794    315849         NaN            0              0  110402225   
1339     6668046    315849         NaN            1              0   24175139   
1390   147758921    323242         NaN            0              0  173782556   
1444   177519685    648878         NaN            4              1  194345673   
1449   342862343         0         NaN           16              0  316732022   
1504    97988610    323242         NaN            0              0  143615197   
1726    37206735    249309         NaN            0              0   95781669   
1896   342368037    244625         NaN            0              0  323759976   
2040   232452800         0         NaN            0              0  127207302   
2135   186934179    315849         NaN            0              0  134217853   
2144    19892648    249309         NaN            3              0   74443459   
2264  1147842298         0         NaN            0              0  303971218   
2572  1114834351    120164         NaN            2              0  870760189   

             set_type          display_date  track_counts tracks  \
146   normal_playlist  2017-11-08T16:05:50Z             0    NaN   
186   normal_playlist  2013-06-12T22:39:55Z             0    NaN   
275   normal_playlist  2013-11-25T06:29:48Z             0    NaN   
414   normal_playlist  2015-04-13T14:42:21Z             0    NaN   
563   normal_playlist  2014-08-04T17:06:28Z             0    NaN   
1171  normal_playlist  2016-05-12T01:06:10Z             0    NaN   
1197  normal_playlist  2015-05-29T00:30:07Z             0    NaN   
1339  normal_playlist  2013-06-12T22:40:23Z             0    NaN   
1390  normal_playlist  2015-09-23T15:08:35Z             0    NaN   
1444  normal_playlist  2015-12-21T20:55:58Z             0    NaN   
1449  normal_playlist  2017-08-04T15:54:33Z             0    NaN   
1504  normal_playlist  2015-04-13T13:42:55Z             0    NaN   
1726  normal_playlist  2014-05-29T21:11:23Z             0    NaN   
1896  normal_playlist  2017-08-02T14:38:41Z             0    NaN   
2040  normal_playlist  2016-06-10T05:03:51Z             0    NaN   
2135  normal_playlist  2016-01-18T20:31:01Z             0    NaN   
2144  normal_playlist  2014-01-13T00:11:49Z             0    NaN   
2264  normal_playlist  2020-10-18T17:45:37Z             0    NaN   
2572  normal_playlist  2020-08-21T16:55:11Z             0    NaN   

     is_purchasable  
146           False  
186           False  
275           False  
414           False  
563            True  
1171          False  
1197          False  
1339          False  
1390          False  
1444          False  
1449          False  
1504          False  
1726          False  
1896          False  
2040          False  
2135          False  
2144          False  
2264          False  
2572          False

In [1058]:
selected_playlist.loc[(selected_playlist['tracks'].isnull()), 'duration'] = 0

In [1059]:
# Kiểm tra việc xử lý bất thống nhất dữ liệu 
selected_playlist[(selected_playlist['tracks'].isnull())]

id  duration       genre  likes_count  reposts_count    user_id  \
146    369995528         0         NaN            7              0  204551380   
186      6668033         0         NaN            0              0   24175139   
275     15500855         0         NaN            1              0   61990827   
414     98000902         0         NaN            0              0  143615197   
563     45791266         0  R&b & soul         7184           2251   21207090   
1171   224254822         0         NaN           59             11  225368471   
1197   111914794         0         NaN            0              0  110402225   
1339     6668046         0         NaN            1              0   24175139   
1390   147758921         0         NaN            0              0  173782556   
1444   177519685         0         NaN            4              1  194345673   
1449   342862343         0         NaN           16              0  316732022   
1504    97988610         0         NaN            0              0  143615197   
1726    37206735         0         NaN            0              0   95781669   
1896   342368037         0         NaN            0              0  323759976   
2040   232452800         0         NaN            0              0  127207302   
2135   186934179         0         NaN            0              0  134217853   
2144    19892648         0         NaN            3              0   74443459   
2264  1147842298         0         NaN            0              0  303971218   
2572  1114834351         0         NaN            2              0  870760189   

             set_type          display_date  track_counts tracks  \
146   normal_playlist  2017-11-08T16:05:50Z             0    NaN   
186   normal_playlist  2013-06-12T22:39:55Z             0    NaN   
275   normal_playlist  2013-11-25T06:29:48Z             0    NaN   
414   normal_playlist  2015-04-13T14:42:21Z             0    NaN   
563   normal_playlist  2014-08-04T17:06:28Z             0    NaN   
1171  normal_playlist  2016-05-12T01:06:10Z             0    NaN   
1197  normal_playlist  2015-05-29T00:30:07Z             0    NaN   
1339  normal_playlist  2013-06-12T22:40:23Z             0    NaN   
1390  normal_playlist  2015-09-23T15:08:35Z             0    NaN   
1444  normal_playlist  2015-12-21T20:55:58Z             0    NaN   
1449  normal_playlist  2017-08-04T15:54:33Z             0    NaN   
1504  normal_playlist  2015-04-13T13:42:55Z             0    NaN   
1726  normal_playlist  2014-05-29T21:11:23Z             0    NaN   
1896  normal_playlist  2017-08-02T14:38:41Z             0    NaN   
2040  normal_playlist  2016-06-10T05:03:51Z             0    NaN   
2135  normal_playlist  2016-01-18T20:31:01Z             0    NaN   
2144  normal_playlist  2014-01-13T00:11:49Z             0    NaN   
2264  normal_playlist  2020-10-18T17:45:37Z             0    NaN   
2572  normal_playlist  2020-08-21T16:55:11Z             0    NaN   

     is_purchasable  
146           False  
186           False  
275           False  
414           False  
563            True  
1171          False  
1197          False  
1339          False  
1390          False  
1444          False  
1449          False  
1504          False  
1726          False  
1896          False  
2040          False  
2135          False  
2144          False  
2264          False  
2572          False

In [1060]:
tracks_na = {'tracks':'" "'}
selected_playlist = selected_playlist.fillna(value=tracks_na)

In [1061]:
# Test sau khi fill na cho tracks
print(f"Số playlist có trường tracks là null: {selected_playlist['tracks'].isnull().sum()}")

Số playlist có trường tracks là null: 0


##### b1.4. genre
- Do có khá nhiều playlist có trường `genre` bằng null, ta sẽ điền giá trị null bằng cách:
    - Ghép hai bảng **playlists** và **tracks**
    - Xác định thể loại của các track thuộc từng playlist và chọn thể loại xuất hiện nhiều nhất làm thể loại của playlist
    
**Lưu ý: Do trường tracks hiện tại đang còn giá trị null nên ta xử lý trường genre sau tracks**

In [1062]:
raw_tracks = pd.read_csv('Crawl_data/tracks.csv', sep='\t')
raw_tracks = raw_tracks[['id', 'genre']]

Để đơn giản, ta bỏ các track có `genre = NaN` để tránh việc genre phổ biến nhất của 5 track là NaN

In [1063]:
raw_tracks = raw_tracks.dropna(subset=['genre'])

In [1064]:
# Fillna cho genre của các playlist

for index, row in selected_playlist.iterrows():
    # chỉ xét các dòng có genre = NaN
    if pd.isna(row['genre']):
        # do ta chỉ lấy 5 track của mỗi playlist nên chỉ cần lấy 5 phần tử đầu của chuỗi tracks
        track_lst = row['tracks'].split(',')[:5] 
        res = raw_tracks.loc[raw_tracks['id'].isin(track_lst)]
        if not res.empty:
            # lấy genre phổ biến nhất trong 5 track của playlist
            selected_playlist.loc[index, 'genre'] = res['genre'].mode()[0]

In [1065]:
# Kiểm tra sau khi xử lý missing value của genre
selected_playlist.isnull().sum()

id                 0
duration           0
genre             67
likes_count        0
reposts_count      0
user_id            0
set_type           0
display_date       0
track_counts       0
tracks             0
is_purchasable     0
dtype: int64

Có vẻ như cách xử lý này đem lại hiệu quả khá tốt khi giảm số lượng giá trị NaN từ 2266 xuống còn 67.

Dự kiến cách xử lý 67 mẫu dữ liệu còn lại là xử lý bằng tay (manual) nên ta sẽ loại các mẫu ít giá trị với đặc điểm sau:
- duration = 0
- duration <> 0, likes_count < 1000 và reposts_count < 1000

Ngưỡng 1000 là giá trị do người lập trình quy định

In [1066]:
# Drop các dòng có duration = 0
duration_0 = selected_playlist[(selected_playlist['duration'] == 0) & (selected_playlist['genre'].isnull())]
selected_playlist = selected_playlist.drop(duration_0.index)

In [1067]:
# Drop các dòng có duration <> 0, likes_count < 1000 hoặc reposts_count < 1000
likes_count_50 = selected_playlist[((selected_playlist['likes_count'] < 1000) | (selected_playlist['reposts_count'] < 1000)) & (selected_playlist['genre'].isnull())]
selected_playlist = selected_playlist.drop(likes_count_50.index)

In [1068]:
# Bằng điều kiện đặt ra, ta giới hạn số mẫu cần kiểm thử bằng tay còn 15 mẫu
selected_playlist.isnull().sum()

id                 0
duration           0
genre             13
likes_count        0
reposts_count      0
user_id            0
set_type           0
display_date       0
track_counts       0
tracks             0
is_purchasable     0
dtype: int64

In [1069]:
selected_playlist[selected_playlist['genre'].isnull()]

id  duration genre  likes_count  reposts_count    user_id  \
27     238501253    523279   NaN        81814           4581   70601494   
105      5914614   3187375   NaN       166616          13606   40174345   
391    745124844    952327   NaN        27358           2415   28970722   
660    232663900   1918277   NaN       191298          17184   70601494   
776    510100800   1772220   NaN        51611           5185   67377000   
938   1055757508   3006484   NaN        40760           2083  577909794   
945    246349810   1952250   NaN       256005          42345   10494998   
1807   620015283   1762922   NaN        31961           4148   46143974   
1887   341715990  48898451   NaN        79448          10413  160760950   
2203   236100282   3263532   NaN       179391          27671    7436630   
2339   537883152   2364732   NaN        42514           2101  351737129   
2373    34518577   5217509   NaN        48966           3222   68485802   
2393     5193173   6407701   NaN         5835           2018   43126413   

             set_type          display_date  track_counts  \
27    normal_playlist  2016-07-04T05:36:20Z             3   
105             album  2013-05-21T20:55:56Z            14   
391   normal_playlist  2019-04-03T23:30:14Z             4   
660   normal_playlist  2016-06-11T01:37:24Z            11   
776   normal_playlist  2018-05-01T01:59:05Z             3   
938   normal_playlist  2020-05-22T04:00:44Z            18   
945   normal_playlist  2016-07-31T22:08:45Z            10   
1807            album  2018-10-10T04:31:11Z            12   
1887  normal_playlist  2017-07-30T20:41:47Z           276   
2203            album  2016-06-24T22:16:31Z            16   
2339            album  2018-06-10T18:09:30Z            16   
2373            album  2014-05-12T02:25:58Z            24   
2393  normal_playlist  2013-04-28T06:47:32Z            14   

                                                 tracks is_purchasable  
27                        272081697,272081435,272080462          False  
105   93264012,93264013,93264014,93264015,93264016,9...          False  
391             600572022,600572007,600571983,600571947          False  
660   268546390,268546291,268546234,268546180,261904...          False  
776                       346168006,377749574,370579751          False  
938   825583921,825583918,825583897,825583876,825583...          False  
945   276206960,276233032,276233401,276233719,276233...          False  
1807  512131077,512131044,512131011,512130987,512130...          False  
1887  284653251,284653159,284653120,284652973,284652...          False  
2203  270727639,270727618,270727583,270727654,270727...          False  
2339  352718012,383347202,383347661,383347925,383345...          False  
2373  149086617,149086625,149086629,149086630,149086...          False  
2393  1053336,5684822,6678666,6523316,6873710,652342...          False

Tiến hành tra cứu từng thể loại của playlist và xử lý missing value của 13 mẫu bằng tay

In [1070]:
selected_playlist.loc[selected_playlist['id'] == 238501253, 'genre'] = 'Alternative Rock'
selected_playlist.loc[selected_playlist['id'] == 5914614, 'genre'] = 'Hip Hop'
selected_playlist.loc[selected_playlist['id'] == 745124844, 'genre'] = 'Hip Hop/Rap'
selected_playlist.loc[selected_playlist['id'] == 232663900, 'genre'] = 'Hip Hop/Rap'
selected_playlist.loc[selected_playlist['id'] == 510100800, 'genre'] = 'Hip hop'
selected_playlist.loc[selected_playlist['id'] == 1055757508, 'genre'] = 'Hip Hop/Rap'
selected_playlist.loc[selected_playlist['id'] == 246349810, 'genre'] = 'Hip Hop/Rap'
selected_playlist.loc[selected_playlist['id'] == 341715990, 'genre'] = 'Hip Hop/Rap'
selected_playlist.loc[selected_playlist['id'] == 236100282, 'genre'] = 'Hip Hop/Rap'
selected_playlist.loc[selected_playlist['id'] == 34518577, 'genre'] = 'Hip hop'
selected_playlist.loc[selected_playlist['id'] == 5193173, 'genre'] = 'Hip hop'
selected_playlist.loc[selected_playlist['id'] == 620015283, 'genre'] = 'Alternative'
selected_playlist.loc[selected_playlist['id'] == 537883152, 'genre'] = 'Pop'

**Sau khi fillna, ta tiếp tục làm sạch trường `genre`**

In [1071]:
selected_playlist['genre'].unique()

array(['Country', 'Hip-hop & Rap', 'Alternative Rock', 'beats',
       'Alternative', 'ESTRENO MUNDIAL', 'Hip hop/rap', 'R&B', 'Hip-hop',
       'Rap', 'Balada', 'Anuel AA', 'Pop', 'Hip Hop/Rap', 'Rap/Hip Hop',
       'RL Grime', 'Rock', 'Hip Hop', 'Kevin Gates', 'Electronic',
       'Remixes', 'Logic', 'R&B & Soul', 'FettyWap', 'AFROHOUSE',
       'Acoustic Pop', 'Dynasty', 'Anuel', 'JASON ALDEAN', 'Dubstep',
       'LAFLAME', 'Classical', 'Tik tok songs', 'Latin', 'Corridos',
       '21-savage', 'RamySabry2020', 'Hip-hop/rap', 'Deep House',
       'Mulatto', 'Young Thug', 'Disclosure', 'Nightcore', '670', 'Lo-fi',
       'Criminal Bassline | Goodie', 'HIPHOP', 'R&b & soul', 'كارول عون',
       'Chill Artistry', 'Shrey_Singhal', 'Electro House', 'Trap',
       'Instermental', 'Dance & EDM', 'Indie', 'ASOC', 'Butta', 'Music',
       'R & B', 'AnuelAA', 'ArianaGrande', 'Hip-hop/Rap', 'Hip-Hop',
       'rap', 'LATIN MUSIC / SALSA', 'Joe Budden', 'LucasColy', 'Chicago',
       'SCHEMATHRA

In [1072]:
invalid_genres = {'ESTRENO MUNDIAL', 'Anuel AA', 'Kevin Gates',
        'Logic', 'FettyWap', 'AFROHOUSE', 'Dynasty', 'Anuel', 'JASON ALDEAN',
       'LAFLAME', '21-savage', 'RamySabry2020','Mulatto', 'Young Thug', 'Disclosure', '670',
       'Criminal Bassline | Goodie', 'كارول عون','Chill Artistry', 'Shrey_Singhal',  
        'ASOC', 'Butta', 'Music', 'AnuelAA', 'ArianaGrande', 'Joe Budden', 'LucasColy', 'Chicago',
       'SCHEMATHRAXX', 'Dillon Cooper', 'Crybaby', 'ReverseBass', 'russ', 'BATON ROUGE',
       'MissingYou', 'Lifestyle', 'OVO', 'JuiceWRLD', 'ISSA',
       'Juicy J', 'ECMG', 'Casa Urbana', 'HH-LA', 'BKBK', 'Calvin Harris', 'youngdolph',
       'mac miller', 'Chopped And Screwed', 'Lil Herb', 'Future', 'borgeous',
       'jacquees', 'Bachata',"Assassin's Creed IV: Black Flag", '☿', 'H8itHere','Drunk Music','Camilla Barbugli',
        'Bryson Tiller',  'kill yourself', 'Human Music', 'Moon', 'TGOD',
       'EDIT', 'bachata', 'film enta omry', 'Mike Stud',
       'GetNMoneyMusic', 'Delusional Thomas', 'Meek Mill', '3HUNNA',
       'Elhae', 'HellaWave', 'Swavey', 'Goa Minimal',
       'FkThisSongButItWillShakeYourCar', 'clarity', 'Hardstyle',
       '25 Nights For Nujabes', 'PUNJAbi', 'Acid Ambient', 'Abdullah',
       'Nipsey Hussle', 'DJ', ":')", 'Futuristic', '1700', 'Arabic', 
        'Carti', 'Roddy Ricch', 'Million',
       'Kompa Love', 'BLove', 'sharmoofers', 'Flume Step', 'BILLO', '100','ACEHOOD', 'Kara_Para', 'JoynerLucas',
       'Computers', 'Diplo', 'Ana Gabriel Mix',
       'BEATS', 'Chenal', 'Dembow 2015', 'CARTERV', 'Major Lazer', 'ASMR',
       'XO', 'Chutney', 'FB:Gary Mackavelli', 'ella mai', 'FBG',
       'Reggaeton',  'Chris Brown', 'Real Hasta La Muerte',
       'DMV', 'DEJ LOAF ', 'Rahn Rahn', 'Damian Marley', 'Speaker Knockerz',
       'Hip-Hop/R&B', 'Matt Corman', 'J Balvin',
       'Mixtape', 'Jah Cure', 'missmulatto', 'Gucci Mane', 'Jhene Aiko', 'blik','CUMBIA MIX', 
       'Bad Vibes Forever', 'Detroit', 'edited', '@newboston',
       'yara', 'Adou Manje Gep', 'Fank', 'LUV', 'Wiz Khalifa', 'Eminem',
       'Origami Sound', 'Drake', 'GUCCIMANE', 'justin bieber',
       'The Kid', 'DJ MUSTARD', 'fuckupcunt',
       'MetroBoominWantSomeMore', 'tory lanez', 'MGK', 'DaBaby', 'Lucki',
       '2 Chainz', 'BFTD', 'arabic', 'ChoppaBoyz Dex Osama', 'youngthug',
       'brent faiyaz ', 'Farhad Darya', 'Cashkidd', 'Bosy',
       'FUNK', 'Swag', 'CHIEF KEEF', 'Imran Khan ', 'John', 'Dlow', 'Bachata Mix', 'ily', 'Memories', '1waycamp',
       'DN Exclusive', 'Gear Up', 'Gaspare Music',
       '808mafia', 'CADA VES QUE TE BAS', 'Dine Alone Records', '70s',
       'Indie, Alternative, Folk, Pop', 'GANG SHIT #112600',
       'Duranguense', 'Chief Keef', 'LostCause', 'Desiigner', 'offonoff', 'Eton Messy', '1738',
       'ChadBahton', 'DESIIGNER', '187', '1017', 'GoonLife',
       'Backyard Sessions', 'promiscuous', 'HELLAWAVE', 'Samurai Guru', 'G Shit Only', 'Punjabi', 'Migos', '6OCLOCK',
       'niykee heaton', 'nav', 'g herbo','All About You ', 'Chiraq', '#DWP15', 'Chingona',
       'PNBRock', 'BLACKSILK', 'SPM', 'RM,'}

In [1073]:
for index, row in selected_playlist.iterrows():
    # chỉ xét các dòng có genre <> NaN
    if not pd.isna(row['genre']):
        if row['genre'] in invalid_genres:
            selected_playlist.loc[index, 'genre'] = np.NaN

In [1074]:
spelling = {'#HIP-HOP':'Hip Hop/Rap', 
            '80s Pop':'Pop',
            'Acoustic Pop':'Pop',
            'Aeroplane Remix':'Remixes',
            'Alternative rock':'Alternative Rock',
            'BACHATA 2014 LATIN':'Latin', 
            'BTS':'Kpop',
            'Balada':'R&B & Soul', 
            'Classic Rock':'Alternative Rock',
            'Corridos Verdes':'Corridos',
            'Dance & edm':'Dance & EDM',
            'Electro':'Electronic', 
            'Electro House':'House', 
            'Electro Swing':'Electronic',
            'Electronic Pop':'Pop',
            'Electronica':'Electronic',
            'Emo Trap':'Trap',
            'Grime Trap':'Trap',
            'HIPHOP':'Hip Hop/Rap', 
            'Hip Hop':'Hip Hop/Rap', 
            'Hip Hop ':'Hip Hop/Rap', 
            'Hip hop':'Hip Hop/Rap',
            'Hip hop/rap':'Hip Hop/Rap', 
            'Hip-Hop':'Hip Hop/Rap', 
            'Hip-Hop/Rap':'Hip Hop/Rap', 
            'Hip-hop':'Hip Hop/Rap',
            'Hip-hop & Rap':'Hip Hop/Rap', 
            'Hip-hop/Rap':'Hip Hop/Rap', 
            'Hip-hop/rap':'Hip Hop/Rap', 
            'HipHop':'Hip Hop/Rap', 
            'Hiphop':'Hip Hop/Rap',
            'Hiphoprap':'Hip Hop/Rap', 
            'Instermental':'Instrumental', 
            'K-POP':'Kpop', 
            'KPOP':'Kpop',
            'LATIN MUSIC / SALSA':'Latin',
            'Latin Urban / Reggaeton':'Reggaeton',
            'Latina':'Latin', 
            'lofi':'Lo-fi', 
            'Metal  ':'Metal',
           'Pop Electro- Pop':'Pop', 
            'R & B':'R&B & Soul', 
            'R&B':'R&B & Soul', 
            'R&b & soul':'R&B & Soul', 
            'RAP':'Hip Hop/Rap', 
            'RL Grime':'Grime',
            'Rap':'Hip Hop/Rap', 
            'Rap/Hip Hop':'Hip Hop/Rap', 
            'Rap/Hip-Hop':'Hip Hop/Rap', 
            'Regional mexicano':'Regional Mexicano',
            'RnB':'R&B & Soul', 
            'Rnb':'R&B & Soul', 
            'Rock':'Alternative Rock', 
            'Shadow rap':'Shadow Rap', 
            'Tik tok songs': 'TikTok Songs',
            'hip hop':'Hip Hop/Rap', 
            'rap':'Hip Hop/Rap',
            'holy':'Pop'
          }
selected_playlist['genre'] = selected_playlist['genre'].replace(spelling)
selected_playlist['genre'] = selected_playlist['genre'].str.capitalize()
selected_playlist['genre'].sort_values().unique()

array(['Acoustic', 'Alternative', 'Alternative folk', 'Alternative rock',
       'Ambient', 'Audiobooks', 'Beats', 'Blues', 'Classical', 'Comedy',
       'Corridos', 'Country', 'Cover', 'Dance', 'Dance & edm',
       'Dancehall', 'Deep house', 'Drill', 'Dubstep', 'Electronic',
       'Entertainment', 'Folk & singer-songwriter', 'Future bass',
       'Grime', 'Hip hop/rap', 'House', 'Indie', 'Instrumental', 'Kpop',
       'Latin', 'Lo-fi', 'Metal', 'Mix', 'Nightcore', 'Oriental',
       'Original', 'Party', 'Pop', 'Punk christmas', 'R&b & soul',
       'Reggae', 'Reggaeton', 'Regional mexicano', 'Remixes', 'Sad',
       'Shadow rap', 'Storytelling', 'Techno', 'Tiktok songs', 'Trance',
       'Trap', 'Waves', 'World', nan], dtype=object)

In [1075]:
# Kiểm tra lần cuối các giá trị missing 
# Lần này ta sẽ bỏ các dòng còn genre = NaN
selected_playlist.isnull().sum()

id                  0
duration            0
genre             282
likes_count         0
reposts_count       0
user_id             0
set_type            0
display_date        0
track_counts        0
tracks              0
is_purchasable      0
dtype: int64

In [1076]:
selected_playlist = selected_playlist.dropna(subset=['genre'])

#### b.3. Biến đổi thuộc tính (data transformation) 

In [1077]:
selected_playlist.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2368 entries, 0 to 2703
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   id              2368 non-null   int64 
 1   duration        2368 non-null   int64 
 2   genre           2368 non-null   object
 3   likes_count     2368 non-null   int64 
 4   reposts_count   2368 non-null   int64 
 5   user_id         2368 non-null   int64 
 6   set_type        2368 non-null   object
 7   display_date    2368 non-null   object
 8   track_counts    2368 non-null   int64 
 9   tracks          2368 non-null   object
 10  is_purchasable  2368 non-null   object
dtypes: int64(6), object(5)
memory usage: 222.0+ KB


- Đổi kiểu dữ liệu `id` và `user_id` thành `string`
- Đổi kiểu dữ liệu `is_purchasable` thành `bool`
- Biến đổi `display_date` thành kiểu `datetime` 

In [1078]:
selected_playlist['id'] = selected_playlist['id'].astype('string')
selected_playlist['user_id'] = selected_playlist['user_id'].astype('string')
selected_playlist['is_purchasable'] = selected_playlist['is_purchasable'].astype('bool')

In [1079]:
selected_playlist['display_date'] = pd.to_datetime(selected_playlist['display_date']).dt.tz_localize(None)

Thêm thuộc tính `display_time = today - display_date`

In [1080]:
from datetime import date
selected_playlist['display_time'] = date.today()

# convert to the same timezone
selected_playlist['display_time'] = pd.to_datetime(selected_playlist['display_time']).dt.tz_localize(None)
selected_playlist['display_time'] = (selected_playlist['display_time'] - selected_playlist['display_date'])/ np.timedelta64(1, 'M')

In [1081]:
# Xóa thuộc tính display_date
selected_playlist = selected_playlist.drop(columns=['display_date'])

### c. Kiểm tra lại mẫu dữ liệu đã chọn

In [1082]:
selected_playlist.head()

id  duration             genre  likes_count  reposts_count  \
0   310741832  40935252           Country         2035            103   
1  1143112054  37740984       Hip hop/rap            0              0   
2   971808526  15552646  Alternative rock           12              0   
3   149404857  66544676             Beats          234             28   
4   361670771   9427177       Alternative         5548            278   

     user_id         set_type  track_counts  \
0  273587555  normal_playlist           189   
1  667588841  normal_playlist           181   
2  769710073  normal_playlist            76   
3  177229326  normal_playlist           203   
4  339239709  normal_playlist            50   

                                              tracks  is_purchasable  \
0  111350611,127711350,89291705,221922037,2557906...           False   
1  877524697,877524238,877523905,877523803,877523...           False   
2  547941324,5284026,579807702,685678354,33010377...           False   
3  19320434,215361560,216352962,43248780,21468388...           False   
4  332962988,333923891,329430750,335860168,308016...           False   

   display_time  
0     43.486187  
1      1.012377  
2      9.603835  
3     61.426899  
4     36.646035

In [1083]:
# Kiểm tra missing value
selected_playlist.isnull().sum()

id                0
duration          0
genre             0
likes_count       0
reposts_count     0
user_id           0
set_type          0
track_counts      0
tracks            0
is_purchasable    0
display_time      0
dtype: int64

In [1084]:
# Kiểm tra kiểu dữ liệu
selected_playlist.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2368 entries, 0 to 2703
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   id              2368 non-null   string 
 1   duration        2368 non-null   int64  
 2   genre           2368 non-null   object 
 3   likes_count     2368 non-null   int64  
 4   reposts_count   2368 non-null   int64  
 5   user_id         2368 non-null   string 
 6   set_type        2368 non-null   object 
 7   track_counts    2368 non-null   int64  
 8   tracks          2368 non-null   object 
 9   is_purchasable  2368 non-null   bool   
 10  display_time    2368 non-null   float64
dtypes: bool(1), float64(1), int64(4), object(3), string(2)
memory usage: 205.8+ KB


In [1085]:
# Kiểm tra số lượng mẫu dữ liệu và số thuộc tính
selected_playlist.shape

(2368, 11)

### d. Lưu xuống file csv để EDA ở module kế tiếp

In [1086]:
selected_playlist.to_csv('Crawl_data/selected_playlists.csv', sep='\t', index=False)

## 2. Tập user

### a. Kiểm tra tổng quan

In [5]:
raw_user = pd.read_csv("Crawl_data/users.csv", sep = '\t')

# Xóa cột index (chỉ đóng vai trò chỉ mục)
raw_user.drop(columns=['index'], inplace=True)

In [6]:
raw_user.shape

(1755, 36)

**Tóm tắt:**

|Thuộc tính|Kiểu dữ liệu|     Ý nghĩa   |Miền giá trị |
|:--------:|:-------------:|:-----:|:-----:|
|**avatar_url**|Chuỗi |Đường dẫn đến ản đại diện của user||
|**created_at**|Thời gian|Thời gian khởi tạo user|   |
|**description**|Chuỗi|Mô tả user của người đăng tải| |
|**city**|Chuỗi|Thành phố user đang sống||
|**country_code**|Chuỗi|Mã quốc gia user đang sống||
|**id**|Kiểu phân loại|Định danh của user||
|**comments_count**|Số nguyên|Số lượt bình luận của user|Liên tục|
|**likes_count**|Số nguyên|Số lượt được yêu thích của user|Liên tục|
|**followers_count**|Số nguyên|Số lượt theo dõi của user|Liên tục|
|**followings_count**|Số nguyên|Số lượt user theo dõi|Liên tục|
|**playlist_likes_count**|Số nguyên|Số lượt được yêu thích các playlist của user|Liên tục|
|**playlist_count**|Số nguyên|Số playlist của user|Liên tục|
|**reposts_count**|Số nguyên|Số bài đăng lại của user|Liên tục|
|**track_count**|Số nguyên|Số lượng track của user|Liên tục|
|**kind**|Chuỗi|Loại đối tượng|user|
|**last_modified**|Thời gian|Lần chỉnh sửa cuối cùng|   |
|**first_name**|Chuỗi|Tên của user|   |
|**last_name**|Chuỗi|Họ của user|   |
|**full_name**|Chuỗi|Tên đầy đủ của user|   |
|**username**|Chuỗi|Tên đăng nhập của user|   |
|**groups_count**|Số nguyên|Số nhóm của user|Liên tục|
|**permalink**|Chuỗi|Đường dẫn cố định của tài nguyên|   |
|**permalink_url**|Chuỗi|Đường dẫn đến trang Soundcloud    |   |
|**uri**|Chuỗi|Đường dẫn API của user|    |
|**url**|Chuỗi|Đường dẫn API của user|    |
|**urn**|Chuỗi|Đường dẫn API của user|    |
|**creator_subscriptions**|Chuỗi|Loại thành viên của user|    |
|**creator_subscription.product.id**|Chuỗi|Loại thành viên của user|    |
|**badges.pro_unlimited'**|Luận lý|User có phải người dùng pro_unlimited không|True hoặc False|
 verified
|**visuals**|Số thực||
|**visuals.urn**|Chuỗi||
|**visuals.enabled**|Chuỗi||
|**visuals.visuals**|Chuỗi||
|**visuals.tracking**|Số thực||

#### a.1. Kiểm tra các thuộc tính định danh

In [7]:
print(f"Số lượng id: {raw_user['id'].nunique()}")
print(f"Số lượng permalink_url: {raw_user['permalink_url'].nunique()}")
print(f"Số lượng avatar_url: {raw_user['avatar_url'].nunique()}")
print(f"Số lượng first_name: {raw_user['first_name'].nunique()}")
print(f"Số lượng last_name: {raw_user['last_name'].nunique()}")
print(f"Số lượng full_name: {raw_user['full_name'].nunique()}")
print(f"Số lượng username: {raw_user['username'].nunique()}")
      
print(f"Số lượng permalink_url: {raw_user['permalink_url'].nunique()}")
print(f"Số lượng permalink: {raw_user['permalink'].nunique()}")
      
print(f"Số lượng uri: {raw_user['uri'].nunique()}")   
print(f"Số lượng url: {raw_user['url'].nunique()}")            
print(f"Số lượng urn: {raw_user['urn'].nunique()}")            

Số lượng id: 1755
Số lượng permalink_url: 1755
Số lượng avatar_url: 1363
Số lượng first_name: 857
Số lượng last_name: 840
Số lượng full_name: 1023
Số lượng username: 1723
Số lượng permalink_url: 1755
Số lượng permalink: 1755
Số lượng uri: 1755
Số lượng url: 1755
Số lượng urn: 1755


#### a.2. Kiểm tra các thuộc tính trùng lắp về mặt ý nghĩa
- `creator_subscriptions`, `creator_subscription.product.id`, `badges.pro_unlimited` đều thể hiện mức độ thành viên mà mỗi người dùng đã đăng ký, do đó chỉ cần chọn trường `creator_subscription.product.id` là đủ

In [10]:
raw_user[['creator_subscriptions', 'creator_subscription.product.id', 'badges.pro_unlimited']]        

creator_subscriptions  \
0                      [{'product': {'id': 'free'}}]   
1                      [{'product': {'id': 'free'}}]   
2                      [{'product': {'id': 'free'}}]   
3     [{'product': {'id': 'creator-pro-unlimited'}}]   
4                      [{'product': {'id': 'free'}}]   
...                                              ...   
1750                   [{'product': {'id': 'free'}}]   
1751                   [{'product': {'id': 'free'}}]   
1752                   [{'product': {'id': 'free'}}]   
1753                   [{'product': {'id': 'free'}}]   
1754                   [{'product': {'id': 'free'}}]   

     creator_subscription.product.id  badges.pro_unlimited  
0                               free                 False  
1                               free                 False  
2                               free                 False  
3              creator-pro-unlimited                  True  
4                               free                 False  
...                              ...                   ...  
1750                            free                 False  
1751                            free                 False  
1752                            free                 False  
1753                            free                 False  
1754                            free                 False  

[1755 rows x 3 columns]

In [22]:
raw_user['creator_subscriptions'].unique()

array(["[{'product': {'id': 'free'}}]",
       "[{'product': {'id': 'creator-pro-unlimited'}}]",
       "[{'product': {'id': 'creator-pro'}}]"], dtype=object)

In [23]:
raw_user['creator_subscription.product.id'].unique()

array(['free', 'creator-pro-unlimited', 'creator-pro'], dtype=object)

#### a.3. Kiểm tra các thuộc tính không đóng góp nhiều vào EDA

In [14]:
print(f"Số lượng groups_count: {raw_user['groups_count'].nunique()}")
print(f"Số lượng kind: {raw_user['kind'].nunique()}")
print(f"Số lượng verified: {raw_user['verified'].nunique()}")
print(f"Số lượng visuals: {raw_user['visuals'].nunique()}")

print(f"Số lượng visuals.enabled: {raw_user['visuals.enabled'].nunique()}")
print(f"Số lượng visuals.tracking: {raw_user['visuals.tracking'].nunique()}")
print(f"Số lượng badges.verified: {raw_user['badges.verified'].nunique()}")
print(f"Số lượng reposts_count: {raw_user['reposts_count'].nunique()}")

Số lượng groups_count: 1
Số lượng kind: 1
Số lượng verified: 1
Số lượng visuals: 0
Số lượng visuals.enabled: 1
Số lượng visuals.tracking: 0
Số lượng badges.verified: 1
Số lượng reposts_count: 0


### Tổng kết

- Thuộc tính `index` là cột chỉ mục. 
- Đối tượng user có 36 thuộc tính, trong đó bao gồm 4 loại thuộc tính chính:
    - Các thuộc tính định danh => Chỉ chọn 1 thuộc tính
        - `id`
        - `avatar_url`
        - `first_name`
        - `last_name`
        - `full_name`
        - `username`
        - `url` 
        - `uri`
        - `urn`
        - `permalink`
        - `permalink_url`
        
    - Các thuộc tính trùng lắp về mặt ý nghĩa:
        - `creator_subscriptions`, `creator_subscriptions.product.id` và `badges.pro_unlimited` (Do đó chỉ cần giữ lại `creator_subscription.product.id`)
       
    - Các thuộc tính không đóng góp đáng kể vào quá trình EDA:
        - `groups_count`
        - `kind`
        - `verified`
        - `visuals`
        - `visuals.enabled`
        - `visuals.tracking`
        - `badges.verified`
        - `reposts_count`
        
    - Các thuộc tính còn lại:
        - `city`
        - `comments_count`
        - `country_code`
        - `created_at`
        - `followers_count`
        - `followings_count`
        - `likes_count`
        - `playlist_likes_count`
        - `playlist_count`
        - `track_count` 
        - `visuals.urn`
        - `visuals.visuals`
        
    - Cuối cùng, đồ án chọn 11 thuộc tính của tập user để EDA:
        - `id`
        - `comments_count`
        - `country_code`
        - `existing_time` (tạo từ thuộc tính `created_at`)
        - `followers_count`
        - `followings_count`
        - `likes_count`
        - `playlist_likes_count`
        - `playlist_count`
        - `track_count`
        - `subscription_type` (đổi tên từ `creator_subscription.product.id`)

In [108]:
# Trong cách cài đặt, ta chọn thêm trường city để phục vụ việc tiền xử lý, sau khi tiền xử lý xong sẽ xóa trường này
selected_columns = ['id', 'city', 'comments_count', 'country_code', 'created_at', 'followers_count',
       'followings_count', 'likes_count', 'playlist_likes_count', 'playlist_count', 'track_count', 
                    'creator_subscription.product.id']
selected_user = raw_user[selected_columns]

### b. Tiền xử lý và feature engineer

In [109]:
selected_user.head()

id    city  comments_count country_code            created_at  \
0  596252733     NaN               0          NaN  2019-02-27T12:14:41Z   
1  557083830  London               7           GB  2018-12-17T23:58:59Z   
2  461702466     NaN              19          NaN  2018-06-12T01:34:24Z   
3   99685284     NaN               0          NaN  2014-06-13T06:02:21Z   
4  774095092     NaN               0          NaN  2020-01-30T15:35:47Z   

   followers_count  followings_count  likes_count  playlist_likes_count  \
0                1                 3           28                     3   
1                4                21          105                     6   
2                3                 8          143                     1   
3          1687347                15           12                     0   
4                2                 0            0                     0   

   playlist_count  track_count creator_subscription.product.id  
0               3            0                            free  
1              15            0                            free  
2               0            0                            free  
3               8          109           creator-pro-unlimited  
4               1            0                            free

In [110]:
selected_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1755 entries, 0 to 1754
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   id                               1755 non-null   int64 
 1   city                             334 non-null    object
 2   comments_count                   1755 non-null   int64 
 3   country_code                     292 non-null    object
 4   created_at                       1755 non-null   object
 5   followers_count                  1755 non-null   int64 
 6   followings_count                 1755 non-null   int64 
 7   likes_count                      1755 non-null   int64 
 8   playlist_likes_count             1755 non-null   int64 
 9   playlist_count                   1755 non-null   int64 
 10  track_count                      1755 non-null   int64 
 11  creator_subscription.product.id  1755 non-null   object
dtypes: int64(8), object(4)
memory usag

#### b.1. Kiểm tra giá trị không hợp lệ

Ta thực hiện kiểm tra sự không hợp lệ và không đồng nhất (cùng một từ nhưng từ viết hoa, từ viết thường,...) với các trường dữ liệu kiểu `categorical` là `country_code`.
- Mã quốc gia sẽ được tham khảo từ link [này](https://countrycode.org/)

In [111]:
# Các mã quốc gia dưới đây đã hợp lệ
selected_user['country_code'].unique()

array([nan, 'GB', 'US', 'ZA', 'BE', 'CA', 'PG', 'UA', 'AL', 'PK', 'NL',
       'HT', 'ES', 'BR', 'EG', 'GE', 'DE', 'AF', 'PR', 'AO', 'AU', 'MX',
       'SE', 'JP', 'BS', 'DK', 'PT', 'CU', 'ID', 'AX', 'NO', 'IT', 'KR'],
      dtype=object)

#### b.2. Kiểm tra giá trị null

In [112]:
selected_user.isnull().sum()

id                                    0
city                               1421
comments_count                        0
country_code                       1463
created_at                            0
followers_count                       0
followings_count                      0
likes_count                           0
playlist_likes_count                  0
playlist_count                        0
track_count                           0
creator_subscription.product.id       0
dtype: int64

**Nhận xét:**
- Để tìm được mã quốc gia của các user có `country_code` bằng NaN, ta có thể tìm đến phần mô tả hoặc parse từ thuộc tính `city` qua. Tuy nhiên, cách xử lý phần `description` đòi hỏi xử lý ngôn ngữ tự nhiên khá nhiều nên ta chỉ rút trích trường `city`, nếu vẫn còn giá trị NaN thì ta thay thế NaN bằng chuỗi "Unknown"

In [113]:
selected_user[(selected_user['country_code'].isnull()) & (~selected_user['city'].isnull())]['city'].sort_values().unique()

array([" L O S '   A N G E L E S", '1320', '1400 1400 1400',
       '8bit wonderland', 'ATK da gang 23FAMILY', 'Atlanta',
       'Atlanta/Decatur', 'B R U H', 'BISEXUAL ', 'Batlimore',
       'Baton Rouge', 'Blazetown 420 ', 'Brooklyn', 'Charlotte',
       'Chicago', 'Chicago, IL', 'Chiraq', 'Corpus Christi, Texas',
       'Dance Pop Songs', 'Denver', 'Detroit', 'East Atlanta', 'HOUSTON',
       'HOUSTON TX', 'Iann Dior Juice Wrld Run', 'Jacksonville, Florida',
       'LA', 'Lil Durk NLE Choppa Damian Marley', 'Los Angeles',
       'Los Angeles County, CA', 'Louisville, KY', 'MIA', 'Memphis',
       'N. Las Vegas', 'NJ/NY', 'New School 80s', 'PLANET DROOL', 'Paris',
       'Paris 20', 'Plastic Inevitable',
       'Playlist OR Spotify Promo Inbox',
       'Promoting Great Music Worldwide', 'Rap~Songs~HipHop~BoomBap~Down',
       'Rod Wave Da Baby', 'SOUTH SYDNEY', 'Shreveport', 'St. Petersburg',
       'TIK TOK', 'The ProducersUnited.com', 'Waynesboro, Pennsylvania ',
       'Wilkes-Bar

In [114]:
invalid_cities = {'New School 80s', 'Lil Durk NLE Choppa Damian Marley', 'ATK da gang 23FAMILY'
       'Playlist OR Spotify Promo Inbox','Promoting Great Music Worldwide', '1400 1400 1400', 
        'near uranus', 'The ProducersUnited.com',
       'da baby da baby da baby', 'playboi carti', 'Iann Dior Juice Wrld Run', 'TIK TOK','PLANET DROOL',
       'Rap~Songs~HipHop~BoomBap~Down','8bit wonderland', 'polo g', 'somewhere scorching.', 
        'Worldwide', 'B R U H', 'tHiS & ThAt WoRlD.. mInI mUsIc CoMp', 'Rod Wave Da Baby',
       'not lil uzi vert', 'BISEXUAL ', 'Dance Pop Songs', '1320', 'Plastic Inevitable'}

In [115]:
for index, row in selected_user.iterrows():
    # chỉ xét các dòng có city <> NaN
    if not pd.isna(row['city']):
        if row['city'] in invalid_cities:
            selected_user.loc[index, 'city'] = np.NaN

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


In [116]:
selected_user[(selected_user['country_code'].isnull()) & (~selected_user['city'].isnull())]['city'].sort_values().unique()

array([" L O S '   A N G E L E S", 'ATK da gang 23FAMILY', 'Atlanta',
       'Atlanta/Decatur', 'Batlimore', 'Baton Rouge', 'Blazetown 420 ',
       'Brooklyn', 'Charlotte', 'Chicago', 'Chicago, IL', 'Chiraq',
       'Corpus Christi, Texas', 'Denver', 'Detroit', 'East Atlanta',
       'HOUSTON', 'HOUSTON TX', 'Jacksonville, Florida', 'LA',
       'Los Angeles', 'Los Angeles County, CA', 'Louisville, KY', 'MIA',
       'Memphis', 'N. Las Vegas', 'NJ/NY', 'Paris', 'Paris 20',
       'Playlist OR Spotify Promo Inbox', 'SOUTH SYDNEY', 'Shreveport',
       'St. Petersburg', 'Waynesboro, Pennsylvania ', 'Wilkes-Barre',
       'calabasas', 'chicago', 'dmv', 'gaia', 'houston', 'philly',
       'pompano beach', 'west. pa', 'weymouth', 'zagazig ,egypt',
       '¥akima '], dtype=object)

In [117]:
spelling = {" L O S '   A N G E L E S": "CA",
            'Atlanta/Decatur':"Atlanta",
            'Chicago, IL':"Chicago", 'Chiraq':"Chicago",
            'Corpus Christi, Texas':"Texas", 'HOUSTON':"Texas",
            'HOUSTON TX':"Texas", 'Jacksonville, Florida':"Florida",
            'Los Angeles':"CA", 'Los Angeles County, CA':"CA",
            'Louisville, KY':"KY", 'Paris 20':"Paris",
            'Waynesboro, Pennsylvania ':"Pennsylvania",
            'houston':"Texas", 'chicago':"Chicago"
           }

In [118]:
selected_user['city'] = selected_user['city'].replace(spelling)
selected_user[(selected_user['country_code'].isnull()) & (~selected_user['city'].isnull())]['city'].sort_values().unique()

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


array(['ATK da gang 23FAMILY', 'Atlanta', 'Batlimore', 'Baton Rouge',
       'Blazetown 420 ', 'Brooklyn', 'CA', 'Charlotte', 'Chicago',
       'Denver', 'Detroit', 'East Atlanta', 'Florida', 'KY', 'LA', 'MIA',
       'Memphis', 'N. Las Vegas', 'NJ/NY', 'Paris', 'Pennsylvania',
       'Playlist OR Spotify Promo Inbox', 'SOUTH SYDNEY', 'Shreveport',
       'St. Petersburg', 'Texas', 'Wilkes-Barre', 'calabasas', 'dmv',
       'gaia', 'philly', 'pompano beach', 'west. pa', 'weymouth',
       'zagazig ,egypt', '¥akima '], dtype=object)

In [120]:
city_country_code = {"Atlanta":"US",
                    'Batlimore':"US",
                    'Baton Rouge':"US",
                    'Blazetown 420 ':"US",
                     'Brooklyn':"US",
                     'CA':"US",
                     'Charlotte':"US",
                     'Chicago':"US",
                     'Denver':"US", 'Detroit':"US", 'East Atlanta':"US", 'Florida':"US", 
                     'KY':"US", 'LA':"US", 'MIA':"US",
                   'Memphis':"US", 'N. Las Vegas':"US", 'NJ/NY':"US", 'Paris':"FR", 'Pennsylvania':"US",
                   'SOUTH SYDNEY':"AU", 'Shreveport':"US",
               'St. Petersburg':"RU", 'Texas':"US", 'Wilkes-Barre':"US", 'calabasas':"US", 'dmv':"US",
               'gaia':"PT", 'philly':"US", 'pompano beach':"US", 'west. pa':"US", 'weymouth':"US",
                   'zagazig ,egypt':"EG", '¥akima ':"US"}

In [121]:
for index, row in selected_user.iterrows():
    # chỉ xét các dòng có city <> NaN
    if not pd.isna(row['city']):
        if row['city'] in city_country_code:
            selected_user.loc[index, 'country_code'] = city_country_code[row['city']]

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


In [125]:
# Kiểm tra sau khi fill country_code từ trường city
selected_user.isnull().sum()

id                                    0
city                               1445
comments_count                        0
country_code                       1408
created_at                            0
followers_count                       0
followings_count                      0
likes_count                           0
playlist_likes_count                  0
playlist_count                        0
track_count                           0
creator_subscription.product.id       0
dtype: int64

- Kiểm tra lại trường `country_code` sau khi tiền xử lý, ta thấy số lượng giá trị null giảm từ 1463 còn 1408. 
- Tiếp tục fill các giá trị na còn lại bằng chuỗi "Unknown" và xóa cột `city`

In [128]:
selected_user = selected_user.drop(columns=['city'])

In [129]:
country_code_na = {'country_code':'Unknown'}
selected_user = selected_user.fillna(value = country_code_na)

In [131]:
# Kiểm tra sau khi fill country_code bằng giá trị "Unknown"
selected_user.isnull().sum()

id                                 0
comments_count                     0
country_code                       0
created_at                         0
followers_count                    0
followings_count                   0
likes_count                        0
playlist_likes_count               0
playlist_count                     0
track_count                        0
creator_subscription.product.id    0
dtype: int64

#### b.3. Biến đổi thuộc tính (data transformation) 

In [132]:
selected_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1755 entries, 0 to 1754
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   id                               1755 non-null   int64 
 1   comments_count                   1755 non-null   int64 
 2   country_code                     1755 non-null   object
 3   created_at                       1755 non-null   object
 4   followers_count                  1755 non-null   int64 
 5   followings_count                 1755 non-null   int64 
 6   likes_count                      1755 non-null   int64 
 7   playlist_likes_count             1755 non-null   int64 
 8   playlist_count                   1755 non-null   int64 
 9   track_count                      1755 non-null   int64 
 10  creator_subscription.product.id  1755 non-null   object
dtypes: int64(8), object(3)
memory usage: 150.9+ KB


- Đổi kiểu dữ liệu `id` thành `string`
- Đổi tên trường `creator_subscription.product.id` thành `subscription_type`
- Biến đổi `created_at` thành kiểu `datetime` và feature engineer thành `existing_time`

In [134]:
selected_user.rename(columns={'creator_subscription.product.id':'subscription_type'}, inplace=True)

In [135]:
selected_user['id'] = selected_user['id'].astype('string')
selected_user['created_at'] = pd.to_datetime(selected_user['created_at']).dt.tz_localize(None)

Thêm thuộc tính `existing_time = today - created_at`

In [137]:
from datetime import date
selected_user['existing_time'] = date.today()

# convert to the same timezone
selected_user['existing_time'] = pd.to_datetime(selected_user['existing_time']).dt.tz_localize(None)
selected_user['existing_time'] = (selected_user['existing_time'] - selected_user['created_at'])/ np.timedelta64(1, 'M')

In [138]:
selected_user = selected_user.drop(columns='created_at')

### c. Kiểm tra lại dữ liệu

In [141]:
selected_user.head()

id  comments_count country_code  followers_count  followings_count  \
0  596252733               0      Unknown                1                 3   
1  557083830               7           GB                4                21   
2  461702466              19      Unknown                3                 8   
3   99685284               0      Unknown          1687347                15   
4  774095092               0      Unknown                2                 0   

   likes_count  playlist_likes_count  playlist_count  track_count  \
0           28                     3               3            0   
1          105                     6              15            0   
2          143                     1               0            0   
3           12                     0               8          109   
4            0                     0               1            0   

       subscription_type  existing_time  
0                   free      20.418975  
1                   free      22.768458  
2                   free      28.975854  
3  creator-pro-unlimited      76.937871  
4                   free       9.342291

In [142]:
# Kiểm tra giá trị missing
selected_user.isnull().sum()

id                      0
comments_count          0
country_code            0
followers_count         0
followings_count        0
likes_count             0
playlist_likes_count    0
playlist_count          0
track_count             0
subscription_type       0
existing_time           0
dtype: int64

In [143]:
# Kiểm tra loại dữ liệu
selected_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1755 entries, 0 to 1754
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id                    1755 non-null   string 
 1   comments_count        1755 non-null   int64  
 2   country_code          1755 non-null   object 
 3   followers_count       1755 non-null   int64  
 4   followings_count      1755 non-null   int64  
 5   likes_count           1755 non-null   int64  
 6   playlist_likes_count  1755 non-null   int64  
 7   playlist_count        1755 non-null   int64  
 8   track_count           1755 non-null   int64  
 9   subscription_type     1755 non-null   object 
 10  existing_time         1755 non-null   float64
dtypes: float64(1), int64(7), object(2), string(1)
memory usage: 150.9+ KB


In [144]:
# Kiểm tra số lượng mẫu và thuộc tính
selected_user.shape

(1755, 11)

### d. Lưu xuống file csv để EDA ở module kế tiếp

In [145]:
selected_user.to_csv("Crawl_data/selected_users.csv", sep='\t', index=False)

## 3. Tập track

### a. Kiểm tra tổng quan

In [151]:
raw_track = pd.read_csv("Crawl_data/tracks.csv", sep='\t')
raw_track = raw_track.drop(columns='index')
raw_track.head()

artwork_url caption  commentable  \
0  https://i1.sndcdn.com/artworks-000104315188-h0...     NaN         True   
1  https://i1.sndcdn.com/artworks-000147808151-gm...     NaN         True   
2  https://i1.sndcdn.com/artworks-000080593908-xr...     NaN         True   
3  https://i1.sndcdn.com/artworks-6xOX1QElJSM0-0-...     NaN         True   
4  https://i1.sndcdn.com/artworks-ClfnOZbcgp4fB4n...     NaN         True   

   comment_count            created_at  \
0          470.0  2015-01-23T11:09:51Z   
1           56.0  2016-02-19T17:44:56Z   
2          291.0  2014-05-27T00:55:57Z   
3          613.0  2018-10-03T00:45:50Z   
4         1207.0  2020-02-13T06:54:20Z   

                                         description  downloadable  \
0  We're proud to introduce the next single by Bo...         False   
1  Download Jacquees "Mood" here: http://www.live...         False   
2                                                NaN         False   
3                                                NaN         False   
4  [VERSE I: Norman Atomic]\r\n\r\nbooked a first...         False   

   download_count  duration  full_duration  ...  \
0             0.0    202362         202362  ...   
1             0.0    231700         231700  ...   
2             0.0    231361         231361  ...   
3             0.0     30000         174749  ...   
4             0.0    133773         133773  ...   

                           publisher_metadata.p_line  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3  Quality Control Music/Young Stoner Life Record...   
4                                                NaN   

               publisher_metadata.p_line_for_display  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3  ℗ Quality Control Music/Young Stoner Life Reco...   
4                                                 ℗    

                           publisher_metadata.c_line  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3  2018 © 2018 Quality Control Music, LLC, under ...   
4                                                NaN   

               publisher_metadata.c_line_for_display  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3  © 2018 © 2018 Quality Control Music, LLC, unde...   
4                                                NaN   

  publisher_metadata.release_title publisher_metadata.iswc visuals.urn  \
0                              NaN                     NaN         NaN   
1                              NaN                     NaN         NaN   
2                              NaN                     NaN         NaN   
3                         Deep End                     NaN         NaN   
4                              NaN                     NaN         NaN   

  visuals.enabled  visuals.visuals visuals.tracking  
0             NaN              NaN              NaN  
1             NaN              NaN              NaN  
2             NaN              NaN              NaN  
3             NaN              NaN              NaN  
4             NaN              NaN              NaN  

[5 rows x 60 columns]

In [153]:
# Kiểm tra số lượng mẫu và thuộc tính
raw_track.shape

(6434, 60)

**Tóm tắt: Tập track hiện tại có 6434 mẫu dữ liệu và 60 thuộc tính**

- Do số lượng thuộc tính khá nhiều và có nhiều thuộc tính trùng lắp với tập user và playlist nên đồ án không tóm tắt lại các thuộc tính thô của tập track mà chỉ liệt kê tên thuộc tính

In [206]:
# Danh sách các thuộc tính của tập track
raw_track.columns

Index(['artwork_url', 'caption', 'commentable', 'comment_count', 'created_at',
       'description', 'downloadable', 'download_count', 'duration',
       'full_duration', 'embeddable_by', 'genre', 'has_downloads_left', 'id',
       'kind', 'label_name', 'last_modified', 'license', 'likes_count',
       'permalink', 'permalink_url', 'playback_count', 'public',
       'purchase_title', 'purchase_url', 'release_date', 'reposts_count',
       'secret_token', 'sharing', 'state', 'streamable', 'tag_list', 'title',
       'uri', 'urn', 'user_id', 'visuals', 'waveform_url', 'display_date',
       'publisher_metadata.id', 'publisher_metadata.urn',
       'publisher_metadata.artist', 'publisher_metadata.contains_music',
       'publisher_metadata.publisher', 'publisher_metadata.isrc',
       'publisher_metadata.writer_composer', 'publisher_metadata',
       'publisher_metadata.album_title', 'publisher_metadata.upc_or_ean',
       'publisher_metadata.explicit', 'publisher_metadata.p_line',
      

#### a.1. Kiểm tra các thuộc tính định danh

In [186]:
print(f"Số lượng id: {raw_track['id'].nunique()}")
print(f"Số lượng permalink_url: {raw_track['permalink_url'].nunique()}")
print(f"Số lượng uri: {raw_track['uri'].nunique()}") 
print(f"Số lượng urn: {raw_track['urn'].nunique()}")    
print(f"Số lượng waveform_url: {raw_track['waveform_url'].nunique()}\n") 

Số lượng id: 6434
Số lượng permalink_url: 6434
Số lượng uri: 6434
Số lượng urn: 6434
Số lượng waveform_url: 6434



#### a.2. Kiểm tra các thuộc tính không đóng góp đáng kể vào EDA

In [190]:
print(f"Số lượng artwork_url: {raw_track['artwork_url'].nunique()}\n")      

# commentable
print(f"Số lượng commentable: {raw_track['commentable'].nunique()}")
print(f"Giá trị của thuộc tính commentable: {raw_track['commentable'].unique()}")
print(f"Phân bố thuộc tính commentable:\n {raw_track['commentable'].value_counts()}\n")
      
# kind
print(f"Số lượng kind: {raw_track['kind'].nunique()}")
print(f"Giá trị của thuộc tính kind: {raw_track['kind'].unique()}\n")
      
# secret_token
print(f"Số lượng secret_token: {raw_track['secret_token'].nunique()}")   
print(f"Giá trị của secret_token: {raw_track['secret_token'].unique()}\n")  
      
# public
print(f"Số lượng public: {raw_track['public'].nunique()}")   
print(f"Giá trị của public: {raw_track['public'].unique()}\n")         
      
# sharing
print(f"Số lượng sharing: {raw_track['sharing'].nunique()}")   
print(f"Giá trị của sharing: {raw_track['sharing'].unique()}\n")  

# tag_list
print(f"Số lượng tag_list: {raw_track['tag_list'].nunique()}\n")   
# print(f"Giá trị của tag_list: {raw_playlist['tag_list'].unique()}")  

# description
print(f"Số lượng description: {raw_track['description'].nunique()}\n")   
# print(f"Giá trị của tag_list: {raw_playlist['description'].unique()}")  
      
# caption
print(f"Số lượng caption: {raw_track['caption'].nunique()}\n")   
      
# state
print(f"Số lượng state: {raw_track['state'].nunique()}")   
print(f"Giá trị của state: {raw_track['state'].unique()}\n")  
    
# streamable
print(f"Số lượng streamable: {raw_track['streamable'].nunique()}")   
print(f"Giá trị của streamable: {raw_track['streamable'].unique()}\n")  
print(f"Phân bố thuộc tính streamable:\n {raw_track['streamable'].value_counts()}\n")      
      
# publisher_metadata
print(f"Số lượng publisher_metadata: {raw_track['publisher_metadata'].nunique()}")   
print(f"Giá trị của publisher_metadata: {raw_track['publisher_metadata'].unique()}\n")  


Số lượng artwork_url: 5792

Số lượng commentable: 2
Giá trị của thuộc tính commentable: [ True False]
Phân bố thuộc tính commentable:
 True     6395
False      39
Name: commentable, dtype: int64

Số lượng kind: 1
Giá trị của thuộc tính kind: ['track']

Số lượng secret_token: 0
Giá trị của secret_token: [nan]

Số lượng public: 1
Giá trị của public: [ True]

Số lượng sharing: 1
Giá trị của sharing: ['public']

Số lượng tag_list: 2433

Số lượng description: 2643

Số lượng caption: 6

Số lượng state: 1
Giá trị của state: ['finished']

Số lượng streamable: 2
Giá trị của streamable: [ True False]

Phân bố thuộc tính streamable:
 True     6426
False       8
Name: streamable, dtype: int64

Số lượng publisher_metadata: 0
Giá trị của publisher_metadata: [nan]



#### a.3. Kiểm tra các thuộc tính tương đồng

Khi xem xét 3 thuộc tính `created_at`, `release_date`, `display_date`, có thể thấy chúng khá liên quan nhau. 
- `created_at` là thời điểm người đăng tải **bắt đầu khởi tạo** track
- `display_date` là thời điểm track thực sự hiển thị sau khi được người đăng tải phát hành
- `release_date` là thời điểm người đăng tải **dự kiến phát hành** track (set trước 1 thời điểm nhất định)

Đồ án chỉ xét thời điểm track thực sự hiển thị công khai trên Soundcloud, tức chỉ chọn thuộc tính `display_date`

In [180]:
raw_track[['created_at', 'display_date', 'release_date']].head()

created_at          display_date          release_date
0  2015-01-23T11:09:51Z  2015-01-23T11:09:51Z                   NaN
1  2016-02-19T17:44:56Z  2016-02-19T17:57:44Z                   NaN
2  2014-05-27T00:55:57Z  2014-05-27T00:55:57Z                   NaN
3  2018-10-03T00:45:50Z  2018-10-05T00:00:00Z  2018-10-05T00:00:00Z
4  2020-02-13T06:54:20Z  2020-02-14T06:36:09Z                   NaN

Khi xem xét 2 thuộc tính `full_duration` và `duration`, ta cũng thấy chúng khá liên quan nhau. 
- `full_duration` là tổng thời gian của mỗi track nhạc
- `duration` là thời gian của đoạn nhạc mẫu user có thể nghe nếu họ chỉ là thành viên miễn phí (free subscription)

Đồ án chỉ xét độ dài thực sự của một track trên Soundcloud, tức chỉ chọn thuộc tính `full_duration`

In [177]:
raw_track[['id','full_duration', 'duration']]

id  full_duration  duration
0     187460600         202362    202362
1     247883444         231700    231700
2     151431689         231361    231361
3     508699284         174749     30000
4     759765964         133773    133773
...         ...            ...       ...
6429  210112634         233633    233633
6430  214258991         246983    246983
6431  655608647         127829    127829
6432  203024128         165291    165291
6433  118351434         173417    173417

[6434 rows x 3 columns]

#### a.4. Kiểm tra các thuộc tính còn lại

In [183]:
# downloadable
print(f"Số lượng downloadable: {raw_track['downloadable'].nunique()}")   
print(f"Giá trị của downloadable: {raw_track['downloadable'].unique()}\n")  
print(f"Phân bố thuộc tính downloadable:\n {raw_track['downloadable'].value_counts()}\n")
      
# download_count
print(f"Số lượng download_count: {raw_track['download_count'].nunique()}\n")  

# has_downloads_left
print(f"Số lượng has_downloads_left: {raw_track['has_downloads_left'].nunique()}")  
print(f"Giá trị của has_downloads_left: {raw_track['has_downloads_left'].unique()}\n")  
print(f"Phân bố thuộc tính has_downloads_left:\n {raw_track['has_downloads_left'].value_counts()}\n")

Số lượng downloadable: 2
Giá trị của downloadable: [False  True]

Phân bố thuộc tính downloadable:
 False    5823
True      611
Name: downloadable, dtype: int64

Số lượng download_count: 506

Số lượng has_downloads_left: 2
Giá trị của has_downloads_left: [ True False]

Phân bố thuộc tính has_downloads_left:
 True     5950
False     484
Name: has_downloads_left, dtype: int64



- Tạm thời với các thuộc tính `publisher_metadata`, ta chỉ xem số lượng giá trị duy nhất.
- Các thuộc tính này có thể được dùng cho bước feature engineer hoặc fill giá trị null

In [201]:
print(f"Số lượng publisher_metadata.id: {raw_track['publisher_metadata.id'].nunique()}") 
print(f"Số lượng publisher_metadata.urn: {raw_track['publisher_metadata.urn'].nunique()}")  
print(f"Số lượng publisher_metadata.artist: {raw_track['publisher_metadata.artist'].nunique()}")             
print(f"Số lượng publisher_metadata.contains_music: {raw_track['publisher_metadata.contains_music'].nunique()}")                   
print(f"Số lượng publisher_metadata.publisher: {raw_track['publisher_metadata.publisher'].nunique()}")                   
print(f"Số lượng publisher_metadata.isrc: {raw_track['publisher_metadata.isrc'].nunique()}")                   
print(f"Số lượng publisher_metadata.writer_composer {raw_track['publisher_metadata.writer_composer'].nunique()}")                   
print(f"Số lượng publisher_metadata.album_title: {raw_track['publisher_metadata.album_title'].nunique()}")                   
print(f"Số lượng publisher_metadata.upc_or_ean: {raw_track['publisher_metadata.upc_or_ean'].nunique()}")    

Số lượng publisher_metadata.id: 4971
Số lượng publisher_metadata.urn: 4971
Số lượng publisher_metadata.artist: 1143
Số lượng publisher_metadata.contains_music: 2
Số lượng publisher_metadata.publisher: 293
Số lượng publisher_metadata.isrc: 3561
Số lượng publisher_metadata.writer_composer 602
Số lượng publisher_metadata.album_title: 1042
Số lượng publisher_metadata.upc_or_ean: 815


In [205]:
# Kiểm tra trường publisher_metadata.id 
raw_track[['id', 'publisher_metadata.id']].head()

id  publisher_metadata.id
0  187460600            187460600.0
1  247883444                    NaN
2  151431689                    NaN
3  508699284            508699284.0
4  759765964            759765964.0

**Tổng kết:**
- Thuộc tính `index` là cột chỉ mục. 
- Đối tượng playlist có 60 thuộc tính, trong đó bao gồm 4 loại thuộc tính chính:
    - Các thuộc tính định danh => Chỉ chọn `id`
        - `id`    
        - `permalink_url`
        - `uri`
        - `urn`
        - `waveform_url`
       
    - Các thuộc tính không đóng góp đáng kể vào quá trình EDA => Không chọn
        - `artwork_url`
        - `commentable`
        - `kind`
        - `secret_token`
        - `public`
        - `sharing`
        - `tag_list`
        - `description`
        - `caption`
        - `state`
        - `streamable`
        - `visuals`
        - `visuals.enabled`
        - `visuals.tracking`
        - `publisher_metadata`
    - Các thuộc tính khá liên quan nên chỉ cần giữ lại 1 trong số chúng
        - `created_at`, `release_date`, và `display_date` => Tạm chọn giữ lại `display_date`
        - `full_duration` và `duration` => Chọn giữ lại `full_duration`
        
    - Các thuộc tính còn lại:
        - `downloadable`
        - `embeddable_by`
        - `genre`
        - `label_name`
        - `last_modified`
        - `license`
        - `likes_count`
        - `permalink`
        - `purchase_title`
        - `purchase_url`
        - `reposts_count`
        - `title`
        
        - `display_date`
        - `playback_count`
        - `visuals.urn`
        - `visuals.visuals`
        - Các thuộc tính `publisher_metadata`
        
- Cuối cùng, đồ án chọn 9 thuộc tính của tập playlist để EDA:
    - `id`
    - `full_duration`
    - `genre`
    - `comment_count`
    - `likes_count`
    - `playback_count`
    - `reposts_count`
    - `download_count`
    - `display_time` (feature engineer từ `display_date`, mang ý nghĩa là thời gian playlist đã hiển thị tính tới thời điểm ngày 05/11/2020)


In [235]:
selected_columns = ['id', 'full_duration', 'genre', 'comment_count', 'likes_count', 'playback_count',
                   'reposts_count', 'download_count', 'display_date']
selected_track = raw_track[selected_columns]

### b. Tiền xử lý và feature engineer

In [236]:
selected_track.head()

id  full_duration              genre  comment_count  likes_count  \
0  187460600         202362  Progressive House          470.0      48016.0   
1  247883444         231700           jacquees           56.0      35182.0   
2  151431689         231361                Rap          291.0      20036.0   
3  508699284         174749            Hip Hop          613.0     103765.0   
4  759765964         133773         shadow rap         1207.0      61040.0   

   playback_count  reposts_count  download_count          display_date  
0       2497040.0           9761             0.0  2015-01-23T11:09:51Z  
1       2584991.0           1764             0.0  2016-02-19T17:57:44Z  
2       1831890.0           1491             0.0  2014-05-27T00:55:57Z  
3       7880344.0           2128             0.0  2018-10-05T00:00:00Z  
4       5024515.0           2400             0.0  2020-02-14T06:36:09Z

In [237]:
selected_track.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6434 entries, 0 to 6433
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   id              6434 non-null   int64  
 1   full_duration   6434 non-null   int64  
 2   genre           5462 non-null   object 
 3   comment_count   6369 non-null   float64
 4   likes_count     6405 non-null   float64
 5   playback_count  6405 non-null   float64
 6   reposts_count   6434 non-null   int64  
 7   download_count  6405 non-null   float64
 8   display_date    6434 non-null   object 
dtypes: float64(4), int64(3), object(2)
memory usage: 452.5+ KB


#### b.1. Kiểm tra giá trị không hợp lệ

Ta thực hiện kiểm tra sự không hợp lệ và không đồng nhất (cùng một từ nhưng từ viết hoa, từ viết thường,...) với các trường dữ liệu kiểu `categorical` là `genre`.

Soundcloud chỉ chứa 41 thể loại nhạc chính thức [(Tham khảo)](https://gist.github.com/Thinkscape/8b98b82a74c102b31f5d) nhưng các giá trị unique của genre lại đạt đến 1047    

In [238]:
selected_track['genre'].nunique()

1047

Do số lượng giá trị unique genre quá nhiều, ta sẽ thực hiện các bước tiền xử lý:
- set `genre = NaN` với các genre có chứa số hoặc ký tự đặc biệt
- viết thường và xóa tất cả các khoảng trắng thừa

In [239]:
selected_track['genre'].sort_values().unique().tolist()

['#DWP15',
 '#HIP-HOP',
 '#Rap',
 '100',
 '1017',
 '1700',
 '1738',
 '187',
 '1waycamp',
 '2 Chainz',
 '2 perc 4 perc 6 perc',
 '21 Savage',
 '21-savage',
 '25 Nights For Nujabes',
 '3HUNNA',
 '432Hz',
 '50 Cent',
 '50 cent',
 '50Cosos',
 '670',
 '678',
 '6OCLOCK',
 '70s',
 '808mafia',
 '80s Pop',
 ":')",
 ':(',
 '</3',
 '<1.5',
 '<3',
 '@TrAmyNig',
 '@newboston',
 'ACEHOOD',
 'AFROHOUSE',
 'AM & Miley',
 'ANDTHENJUST',
 'ASMR',
 'ASOC',
 'ASOT 700',
 'ASTRALWAVE',
 'Abdullah',
 'AceHood',
 'Acid Ambient',
 'Acoustic',
 'Acoustic Pop',
 'Add Tags',
 'Addicted',
 'Adou Manje Gep',
 'Aeroplane Remix',
 'Ajjae',
 'All About You ',
 'All that matters',
 'Alternative',
 'Alternative Folk',
 'Alternative Rap',
 'Alternative Rock',
 'Alternative Spoken Word',
 'Ambient',
 'Ana Gabriel Mix',
 'Anuel',
 'Anuel AA',
 'AnuelAA',
 'Arabic',
 'Ariana Grande',
 'ArianaGrande',
 "Assassin's Creed IV: Black Flag",
 'Audiobooks',
 'BACHATA 2014 LATIN',
 'BACKENDCHILD',
 'BATON ROUGE',
 'BBO',
 'BCX',
 

In [240]:
import re

for index, row in selected_track.iterrows():
    # chỉ xét các dòng có genre <> NaN
    if not pd.isna(row['genre']):
        if (re.search(r'\d', row['genre'])) or ((not re.search('^[a-zA-Z0-9]*$', row['genre'])) and ('#' not in row['genre'])):
            selected_track.loc[index, 'genre'] = np.NaN

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


In [241]:
# Kiểm tra sau khi loại các genre chứa số và ký tự đặc biệt
selected_track['genre'].nunique()

549

Chỉnh các genre đều thành chữ viết thường

In [242]:
selected_track['genre'] = selected_track['genre'].str.lower()

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Xóa các khoảng trắng thừa

In [243]:
selected_track['genre'] = selected_track['genre'].str.strip()

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Xóa ký tự hashtag #

In [247]:
selected_track['genre'] = selected_track['genre'].str.strip('#')

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [249]:
# Kiểm tra sau khi đồng bộ chữ viết thường và loại khoảng trắng thừa
selected_track['genre'].nunique()

486

In [259]:
selected_track['genre'] = selected_track['genre'].str.capitalize()
# selected_track['genre'].sort_values().unique()

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [258]:
invalid_genres = {'Abdullah', 'Acehood', 'Addicted','Afroman', 'Ajjae', 
                  'Andthenjust', 'Anuel', 'Anuelaa', 'Arianagrande', 'Asmr',
           'Asoc', 'Astralwave', 'Atif', 'Ayookd', 'Bachata',
       'Backendchild', 'Balllikeimkobe', 'Bankhead', 'Bbo', 'Bcx', 'Bftd',
       'Billionaireblack', 'Billo', 'Bkbk', 'Blacklivesmatter',
       'Blacksilk', 'Blik', 'Blove', 'Blow', 'Bmike', 'Borgeous', 'Bosscash', 'Bosy', 'Bounce', 'Brandy',
       'Bryson',  'Butta', 'Carnage', 'Carterv', 'Carti', 'Cash',
       'Cashcarti', 'Cashkidd', 'Cdot', 'Chadbahton', 'Chenal', 'Chicago',
       'Chiefkeef', 'Chill', 'Chillstep', 'Chingona', 'Chiraq',
       'Christmas', 'Chutney', 'Clarity', 'Clariyahboss', 'Clasicos',
       'Cmdwn', 'Comeupkid', 'Computers', 'Cozmik', 'Crenshaw', 'Crime',
       'Crybaby', 'Cure', 'Dababy', 'Daedae', 'Danielaandrade', 'Dank', 'Dark', 'Deep', 'Desiigner', 'Detroit',
       'Diplo', 'Disclosure', 'Dj', 'Djbfront', 'Djtaj', 'Dlow', 'Dmv',
       'Dongan', 'Donkstep', 'Dope', 'Dopplebangers', 'Drake', 'Drumstep', 'Drunkinlove', 'Dt', 
       'Dumb', 'Duranguense', 'Duranguensemix', 'Dutty', 'Dynasty',
       'Dystopian', 'Ecmg', 'Eden', 'Edit', 'Edited', 'Effortless', 'Elhae', 'Eminem', 'Experimental',
       'Fank', 'Fbg', 'Fbgduck', 'Fetty', 'Fettywap', 'Finallyrich',
       'Fkthissongbutitwillshakeyourcar', 'Flavors', 'Flex',
       'Flosstradamus', 'Fuckupcunt', 'Fugazi', 'Gamda', 'Gangshit', 'Gangsta', 'Garage', 'Gas',
       'Gbe', 'Getnmoneymusic', 'Ghazal', 'Ghostemane', 'Goblinost',
       'Gocrazy', 'Goonlife', 'Gorillaz', 'Greaf',
       'Groove', 'Grunge', 'Guccimane', 'Guitar', 'Guiz', 'Hahahahaha',
       'Harder', 'Hardstyle', 'Hardstyles',
       'Heartbrokerecords #seeninsilence #confusethemasses #letthebeatspeak',
       'Heat', 'Hellawave', 'Hellawaveboyz', 'High', 'Icamefromnothing', 'Ily', 
       'Infamousrell', 'Issa', 'Itwillallbeoversoon', 'Jacquees', 'Jayo', 'Jeezy',
       'Jheneaiko', 'Jid', 'Jinsang', 'Jmm', 'John', 'Joji', 'Jory',
       'Joynerlucas', 'Juice', 'Juicewrld', 'Juke', 'Jungleterror',
       'Jusglo', 'Justinbieber', 'Kabhi', 'Kanan', 'Kanyewest',
       'Kasaantv', 'Kendricklamar', 'Kerala', 'Keyshiacole',
       'Kidsthealbum', 'Kiiara', 'Kill', 'Killstation', 'Kings',
       'Kodakblack', 'Kondzilla', 'Kpa', 'Ksrgroup', 'Kygo',
       'Laflame', 'Laryover', 'Ldru', 'Lean', 'Leaving', 'Leonbridges', 'Life', 'Lifestyle', 'Like',
       'Lildurk', 'Liljon', 'Lilmouse', 'Lilpeep', 'Little', 'Littness',
       'Liveforever', 'Logic', 'Londonjae', 'Lostcause', 'Love',
        'Lucascoly', 'Lucki', 'Lukebryan', 'Luv',  'Mambo #nicky #jam #nickyjam #elperdon #elperdonremix',
       'Manalitrance', 'Mariah', 'Martygrimes', 'Mattybraps',
       'Melanie', 'Melaniemartinez', 'Melbournebounce', 'Melodic',
       'Memories', 'Memphis', 'Memphistn', 'Mere', 'Metroboominwantsomemore', 
                  'Mgk', 'Migos', 'Million', 'Missingyou',
       'Missmulatto', 'Mitali', 'Mm', 'Moans', 'Moon',
       'Mozzy', 'Mulatto', 'Music', 'Nashvillemusichouse', 'Nasty', 'Nav',
       'New', 'Newsound', 'Ninja',
       'Nipseyhussle', 'Niykeeheaton', 'Nocopyrightsounds', 'Noisestorm',
       'Not', 'Nowimjoey', 'Offonoff', 'Offspring', 'Oh', 'Old', 'Oldies',
       'Orchestralcrunkwave', 'Otf', 'Outkast',
       'Ovo', 'Pashto', 'Philthyrich', 'Phonk', 'Pink',
       'Playboicarti', 'Playboifresh', 'Playbook', 'Plies', 'Plurnt',
                     'Problematic', 'Promiscuous',
       'Promnite', 'Punjabi', 'Purp', 'Pusho',
       'Queen', 'Quemix', 'Quilly', 'Radha', 'Rahnrahn', 'Rain', 'Ramy',
       'Rare', 'Raw', 'Redman', 'Remyboyz',
       'Retromusicgroup', 'Riff', 'Rightnow', 'Rihanna',
       'Robotaki', 'Romiti', 'Rondonumbanine',
       'Rudimental', 'Runnaway', 'Russ', 'Sangatost', 'Scfirst', 'Schema', 'Schemathraxx', 'Screwston',
       'Sdot', 'Serise', 'Sesh', 'Sevyn', 'Shaggy', 'Share',
       'Sharmoofers', 'Simpshit', 'Sixset', 'Skizzy', 'Skrillex', 'Skt',
       'Sktexclusive', 'Skyfall', 'Slipknot', 'Slipsoknot', 'Slowjams',
       'Smooth', 'Soul', 'Soulection', 'Soulful', 'Soundtrack',
       'Southpaw', 'Spm', 'Sremmlife', 'Steve', 'Storytelling',
       'Streetpoem', 'Study', 'Supportsexworkers', 'Swag', 'Swavey',
       'Sway', 'T', 'Tbg', 'Teammulatto', 'Teemid',
       'Tekstyle', 'Tgod', 'Throwback', 'Thug', 'Thugstep',
       'Tomorrowland', 'Toosmooth', 'Torylanez', 'Tracks', 'Tracy',
       'Travisscott', 'Trell', 'Trillsammy', 'Triphop', 'Tropical',
       'Twerk', 'Tyga', 'Tylerthecreator', 'Uber', 'Uwu',
       'Va', 'Vaporwave', 'Var', 'Variado', 'Vibe',
       'Vine',  'Void', 'Wax', 'Wayout', 'Wedidit',
       'Werkkk', 'Wiz', 'Wood', 'Work', 'Xo',
       'Xxx', 'Yara', 'Yazzie', 'Yoga', 'Yonkers', 'Youngdolph',
       'Younghustlers', 'Youngthug', 'Youngthug#youtheone#richgang',
       'Zafar', 'Zara', 'Zeeshan', 'Zen', 'Zidd', 'Zombies', 'Zonemusic',
       'Zouk'
       }

In [260]:
for index, row in selected_track.iterrows():
    # chỉ xét các dòng có genre <> NaN
    if not pd.isna(row['genre']):
        if row['genre'] in invalid_genres:
            selected_track.loc[index, 'genre'] = np.NaN

/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


In [254]:
spelling = {'Afrohouse':'House',
            'Balada':'Ballad',
            'Bassnectar':'Bass',
            'Bedroombass':'Bass',
            'Blueorred':'Blues',
            'Bts':'Kpop',
            'Drillmusic #hiphop':'Hip hop/rap',
            'Electro':'Electronic',
            'Electro #future trap':'Electronic',
            'Electronica':'Electronic',
            'Elettronica':'Electronic',
           'Folk': 'Folk & Singer-Songwriter',
            'Futuristic':'Future',
            'Goldhouse':'House',
            'Hip-hop':'Hip hop/rap', 'Hiphop':'Hip hop/rap',
           'Hiphoprap':'Hip hop/rap', 
            'Instermantal':'Instrumental', 'Instermental':'Instrumental',
            'Jazzbumps':'Jazz',
            'Latina':'Latin',
            'Love #nightcore':'Nightcore',
            'Luvfi':'Lo-fi', 'Lofi':'Lo-fi',
            'Metalcore':'Metal',
            'Mixtape': 'Mix',
            'Nightcorereality':'Nightcore',
            'Yg':'Kpop',
            'Worldmusic':'World',
            'Vibes #country #mix':'Country',
            'Traplatino':'Trap', 'Trapmusic':'Trap', 'Trapsoul':'Trap',
            'Techhouse':'House',
            'Sadtrap':'Trap',
             'Rnb':'R&b & soul',
            'Rnbass':'R&b & soul', 'Rnbhiphop':'R&b & soul',
            'Rock':'Alternative Rock', 
            'Romanticas':'Romance', 'Romantico':'Romance',
            'Pos':'Pop', 'Pnbrock':'Hip hop/rap', 'Pnb':'Hip hop/rap',
            'Psyreggae':'Reggae', 'Rap':'Hip hop/rap',
            'Remixes':'Remix', 'Remtrex':'Remix',
            'Reggiecouz':'Reggae', 
            'Reversebass':'Bass'
           }

In [262]:
selected_track['genre'] = selected_track['genre'].replace(spelling)


/home/nnbtam99/miniconda3/envs/pysyft/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [266]:
# Kiểm tra các genre sau khi xử lý
print(selected_track['genre'].nunique())
selected_track['genre'].sort_values().unique()

60


array(['Acoustic', 'Alternative', 'Alternative Rock', 'Ambient', 'Anime',
       'Arabic', 'Audiobooks', 'Ballad', 'Bass', 'Beats', 'Blues',
       'Classical', 'Comedy', 'Corridos', 'Country', 'Cover', 'Dance',
       'Dancehall', 'Drill', 'Dubstep', 'Electronic', 'Entertainment',
       'Folk & Singer-Songwriter', 'Funk', 'Future', 'Grime',
       'Hip hop/rap', 'Holy', 'House', 'Indie', 'Instrumental', 'Jazz',
       'Kpop', 'Latin', 'Learning', 'Lo-fi', 'Lullaby', 'Mashup', 'Metal',
       'Mix', 'Nightcore', 'Oriental', 'Original', 'Piano', 'Pop', 'Punk',
       'R&b & soul', 'Reggae', 'Reggaeton', 'Remix', 'Romance', 'Sad',
       'Salsa', 'Techno', 'Trance', 'Trap', 'Underground', 'Vocaloid',
       'Waves', 'World', nan], dtype=object)

#### b.2. Kiểm tra giá trị null (missing value)

In [267]:
selected_track.isnull().sum()

id                   0
full_duration        0
genre             5335
comment_count       65
likes_count         29
playback_count      29
reposts_count        0
download_count      29
display_date         0
dtype: int64

Tiến hành xử lý null các trường `comment_count`, `likes_count`, `playback_count`, `download_count` và `genre`

##### b2.1. Các trường số thực 
Bao gồm:
- `comment_count`
- `likes_count`
- `playback_count`
- `download_count`

In [271]:
selected_track[selected_track['comment_count'].isnull()].head()

id  full_duration  genre  comment_count  likes_count  \
64   206333759         262371  Indie            NaN          NaN   
195  211341283         158720    NaN            NaN       1621.0   
216  118023933          70222    NaN            NaN          NaN   
267  262703709         107530    NaN            NaN      83459.0   
316  753932167         144091    NaN            NaN      56102.0   

     playback_count  reposts_count  download_count          display_date  
64              NaN              0             NaN  2015-05-20T15:03:37Z  
195        967883.0            273             8.0  2015-06-21T17:24:36Z  
216             NaN              0             NaN  2013-11-01T00:39:13Z  
267       6577883.0           8460         26772.0  2016-05-05T23:51:17Z  
316       4138462.0            914            25.0  2020-02-02T19:57:56Z

**Một đề xuất đơn giản là ta có thể fillna cho các trường số thực bằng giá trị 0**

In [273]:
float_na = {'comment_count':0,
           'likes_count':0,
           'playback_count':0,
           'download_count':0}
selected_track = selected_track.fillna(value=float_na)

In [274]:
# Kiểm tra sau khi xử lý null cho các trường số thực
selected_track.isnull().sum()

id                   0
full_duration        0
genre             5335
comment_count        0
likes_count          0
playback_count       0
reposts_count        0
download_count       0
display_date         0
dtype: int64

##### b2.2. genre
Với trường `genre` của track, ta giải quyết null bằng cách gán nó bằng chuỗi "Unknown"

In [275]:
genre_na = {'genre':"Unknown"}
selected_track = selected_track.fillna(value=genre_na)

#### b.3. Biến đổi thuộc tính (data transformation) 

In [277]:
selected_track.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6434 entries, 0 to 6433
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   id              6434 non-null   int64  
 1   full_duration   6434 non-null   int64  
 2   genre           6434 non-null   object 
 3   comment_count   6434 non-null   float64
 4   likes_count     6434 non-null   float64
 5   playback_count  6434 non-null   float64
 6   reposts_count   6434 non-null   int64  
 7   download_count  6434 non-null   float64
 8   display_date    6434 non-null   object 
dtypes: float64(4), int64(3), object(2)
memory usage: 452.5+ KB


- Biến đổi `id` thành kiểu `string`
- Biến đổi `display_date` thành kiểu `datetime`
- Biến đổi `comment_count`, `likes_count`, `playback_count` và `download_count` về kiểu `int64`

In [280]:
selected_track['display_date'] = pd.to_datetime(selected_track['display_date']).dt.tz_localize(None)

Thêm thuộc tính `display_time = today - display_date`

In [281]:
selected_track['display_time'] = date.today()

# convert to the same timezone
selected_track['display_time'] = pd.to_datetime(selected_track['display_time']).dt.tz_localize(None)
selected_track['display_time'] = (selected_track['display_time'] - selected_track['display_date'])/ np.timedelta64(1, 'M')

In [283]:
# Xóa cột display_date sau khi feature engineer
selected_track = selected_track.drop(columns=['display_date'])

In [287]:
# Biến đổi các trường về kiểu int64
selected_track['comment_count'] = selected_track['comment_count'].astype('int')
selected_track['likes_count'] = selected_track['likes_count'].astype('int')
selected_track['playback_count'] = selected_track['playback_count'].astype('int')
selected_track['download_count'] = selected_track['download_count'].astype('int')

### c. Kiểm tra lại mẫu dữ liệu đã chọn

In [291]:
selected_track.head()

id  full_duration        genre  comment_count  likes_count  \
0  187460600         202362      Unknown            470        48016   
1  247883444         231700      Unknown             56        35182   
2  151431689         231361  Hip hop/rap            291        20036   
3  508699284         174749      Unknown            613       103765   
4  759765964         133773      Unknown           1207        61040   

   playback_count  reposts_count  download_count  display_time  
0         2497040           9761               0     69.571361  
1         2584991           1764               0     56.682940  
2         1831890           1491               0     77.503395  
3         7880344           2128               0     25.199696  
4         5024515           2400               0      8.861780

In [292]:
# Kiểm tra loại dữ liệu
selected_track.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6434 entries, 0 to 6433
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   id              6434 non-null   int64  
 1   full_duration   6434 non-null   int64  
 2   genre           6434 non-null   object 
 3   comment_count   6434 non-null   int64  
 4   likes_count     6434 non-null   int64  
 5   playback_count  6434 non-null   int64  
 6   reposts_count   6434 non-null   int64  
 7   download_count  6434 non-null   int64  
 8   display_time    6434 non-null   float64
dtypes: float64(1), int64(7), object(1)
memory usage: 452.5+ KB


In [293]:
# Kiểm tra missing value
selected_track.isnull().sum()

id                0
full_duration     0
genre             0
comment_count     0
likes_count       0
playback_count    0
reposts_count     0
download_count    0
display_time      0
dtype: int64

### d. Lưu dữ liệu xuống file csv

In [294]:
selected_track.to_csv('Crawl_data/selected_tracks.csv', sep='\t', index=False)